### ISSUE TITLE
ko apply doesn't error out when import path is incorrect

### ISSUE THREAD

**Issue by dprotaso** [google/ko#10]
I mistyped a package name when specifying my container image. This caused `ko` to apply a yaml configuration with an non-existent image.

It would be nice if `ko` checked if the images I'm applying exist in my image registry and error out if they do not.

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/58

**Comment by vickynarang01** [comment]
I am getting an error on firing this command: ko resolve -f deployment.yaml
<img width="1680" alt="Screenshot 2021-09-03 at 1 46 44 PM" src="https://user-images.githubusercontent.com/33773215/131973774-bde04899-730c-4a6d-a9a4-b12631dd3573.png">

Attached a deployment yaml here for reference and the output of the command.
<img width="1680" alt="Screenshot 2021-09-03 at 1 51 15 PM" src="https://user-images.githubusercontent.com/33773215/131974311-1071725a-ef9f-44bc-8d6e-7bb4df03d746.png">


Error: error processing import paths in "deployment.yaml": error resolving image references: found strict reference but ko://github.com/vickynarang01/helloworld is not a valid import path: no required module provides package github.com/vickynarang01/helloworld; to add it:

Don't understand what's wrong here

**Comment by imjasonh** [comment]
There are a few things that could cause this:

- Is the repo checked out in your `$GOPATH`?
- I see the repo isn't using go modules, running `go mod init github.com/vickynarang01/helloworld` then `ko resolve` again should help.
