### ISSUE TITLE
Adopt gopkg.in/yaml.v3

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#101]
According to @dprotaso, v3 will allow us to transform yaml while preserving comments, which is somewhat related to https://github.com/google/ko/issues/39

> At a minimum the adoption of the internal yaml.v3::Node type would preserve comments and formatting when ko’ing

Which would be so so wonderful.

**Comment by dprotaso** [comment]
Here's how I used it

https://github.com/dprotaso/projectriff-k8s-manifest-scanner/blob/master/pkg/scan/resolve.go#L26-L81
