### ISSUE TITLE
resolve with tag should use the full reference

### ISSUE THREAD

**Issue by vdemeester** [google/ko#108]
If I do a `ko resolve` with `-t/--tags`, we should be able to use the full reference in the resolve yaml files, aka something like `gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.6.0@sha256:43050320e994156a2683ab5d30551a52a4a59fe20b0ee50161af5d524b9aa5c6` where both the `tag` and the `digest` is present.

Few potential questions:
1. what to do if there is multiple tags provided `-t` is an array flag :angel: ?
2. should it do it by default or should we have an option for it ?

/cc @jonjohnsonjr @bobcatfish @ImJasonH 

Related issue https://github.com/tektoncd/pipeline/issues/1232

**Comment by jonjohnsonjr** [comment]
I so, so desperately hate this syntax and wish it would go away 😄

**Comment by vdemeester** [comment]
> I so, so desperately hate this syntax and wish it would go away :smile: 
Lol, I hear you :stuck_out_tongue_closed_eyes: 

> We could do it if and only if there is one, non-`latest` tag specified? It _would_ be nice for releases...

That was kinda my thought (and the use case we have for tekton :angel: ).

**Comment by jonjohnsonjr** [comment]
Took a stab at it, LMK what you think.
