### ISSUE TITLE
ko apply seems to fail silently

### ISSUE THREAD

**Issue by poy** [google/ko#110]
We are running `ko` in our CI and noticed that our project is not being installed properly. It turned out to be a dependency issue, but `ko` was not failing.

Is there a way to ensure `ko` returns a non-0 exit code and some information instead of creating pods that have the image `github.com/someorg/someproject/cmd/asdf`?

**Comment by ImJasonH** [comment]
This is possibly solved by #58 which I realize now isn't actually documented anywhere 😅

**Comment by poy** [comment]
Ah ok! I'll give this a try.

**Comment by poy** [comment]
@ImJasonH This did in fact help! Thanks!
