### ISSUE TITLE
Support for kustomize in ko

### ISSUE THREAD

**Issue by afrittoli** [google/ko#115]
`kubectl` supports deploying YAML manifests with kustomize overlays via the `-k` option, where `kubectl apply -k <path>` roughly corresponds to `kustomize <path> | kubectl apply -f -`.

It would be handy to have a similar support kustomize in the `resolve` and `apply` commands of `ko`. That would enable maintaining overlays for applications deployed with `ko`.

For instance, when developing Knative or Tekton, it may be necessary to add special secrets or rolebindings to service accounts, depending on the target development cluster. Local overlays can be maintained for this purpose, which make the development workflow easier.

This is possible today with `kustomize <path> | ko apply -f -`, so `ko apply -k` would be a nice to have.

**Comment by jonjohnsonjr** [comment]
What would this implementation look like?

My gut reaction is "no" because I'd prefer to keep `ko` simple, but if all you have to do is pass through some flags it wouldn't be a huge deal.

What does the kubernetes implementation look like? Do they import kustomize or just shell out to it?

**Comment by EronWright** [comment]
@jonjohnsonjr the Kustomize API was recently factored out from the CLI, for tool integration purposes. The docs are pretty sparse AFAIK, but see a mention in [`versioningPolicy.yaml`](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/versioningPolicy.md#go-api-versioning).
