### ISSUE TITLE
Publish a Resolved Manifest

### ISSUE THREAD

**Issue by josephlewis42** [google/ko#118]
Ko should support publishing a resolved manifest in an image alongside the released images.

Ideally, this functionality would support a custom base-image (or maybe directory structure) and a location in that image to put the resolved manifest.

This should allow users to publish Helm3 compatible OCI chart images, and [GCP Marketplace App Packages](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package) if the right deployer was used.

**Comment by jonjohnsonjr** [comment]
Can you describe what you mean by "resolved manifest"?

This seems possible today with `ko resolve`, see the [Relevance to Release Management](https://github.com/google/ko#relevance-to-release-management) section in the README.

**Comment by josephlewis42** [comment]
Sure, I do mean storing the results of `ko resolve` in a container next to the other containers that were generated by resolve. This would allow `ko` to be "atomic".

Since the resolved YAML is in a container, you can easily tag it, manage ACLs with the other images, and allow other containers to be built from it e.g. a Helm chart or [GKE App Package](https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package) which is basically a home-rolled version of the operator pattern.

**Comment by josephlewis42** [comment]
Closing this in favor of: https://github.com/google/ko/issues/128 as that would suit out needs equally well
