### ISSUE TITLE
Support Environment Variable Configuration

### ISSUE THREAD

**Issue by josephlewis42** [google/ko#130]
We're running `ko` in a pipeline where we're dynamically creating the base image, it would be helpful to be able to specify the full configuration as environment variables.

It looks like this module uses Viper, and they support dynamically generating bindings to environment variables with an optional prefix (like `KO_`):

https://github.com/spf13/viper#working-with-environment-variables

**Comment by jonjohnsonjr** [comment]
That seems like it would work well with [defaultBaseImage](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/pkg/commands/config.go#L93), but it's not clear to me (from scanning the docs) how you would specify the [baseImageOverrides](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/pkg/commands/config.go#L101) map using environment variables.

**Comment by josephlewis42** [comment]
I think you supply it as a JSON map: [GetStringMapString](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/vendor/github.com/spf13/viper/viper.go#L784:6) calls [cast.ToStringMapString](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/vendor/github.com/spf13/cast/cast.go#L108:6) which calls [ToStringMapStringE](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/vendor/github.com/spf13/cast/caste.go#L855:6) which has type specific implmentations; for strings provided by environment variables it should call [jsonStringToObject](https://github.com/google/ko/blob/d24b60a88f1afe586ab07b312453da921b44cc51/vendor/github.com/spf13/cast/caste.go#L1246:6) which tries to extract the value as a JSON map.
