### ISSUE TITLE
Delete Order

### ISSUE THREAD

**Issue by karlkfi** [google/ko#135]
It seems like `ko delete -f dir/` deletes everything in a folder in the same order it was installed, which is usually backwards from what's desirable. Is there any way to control delete order or make it delete in reverse order?

**Comment by jonjohnsonjr** [comment]
There's not any way to do this right now. I tried to convinced `tac(1)` to do this, but couldn't get splitting on `---` to work correctly.

I think we'd need to bake this logic into `ko delete` to get it to work. We currently just pass through to `kubectl delete`, but it might be worth the effort to implement traversing the documents in reverse.
