### ISSUE TITLE
Support `ko login`

### ISSUE THREAD

**Issue by mattmoor** [google/ko#155]
`ko` consumes the Docker keyring, but generally it is a pain in the butt to configure this without Docker installed.

I propose we add `ko login` mimicing the behavior of `docker login` so that folks can reasonable authenticate without having docker installed.

This likely needs work in github.com/google/go-containerregistry, and come to think of it a `crane login` command sounds useful too!

**Comment by mattmoor** [comment]
@jonjohnsonjr since you added `crane auth login` 👀

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/243

**Comment by alexellis** [comment]
Hi guys, the README file says `ko auth login` exists, but go get with the latest stable release doesn't seem to support it.

Is the resolution to pull the master version or is that a bug?

Alex

**Comment by jonjohnsonjr** [comment]
Yeah... https://github.com/google/ko/pull/243#issuecomment-724269021

I can refactor some things to make this less gross (we just want `ko login` not `ko auth login`, IMO.

**Comment by alexellis** [comment]
I would like to see some output, if you're open to it after running the login command like `Wrote to... ~/.docker/config.json` or some other output if the file wasn't updated (because it already existed)

**Comment by jonjohnsonjr** [comment]
> I would like to see some output, if you're open to it after running the login command like Wrote to... ~/.docker/config.json or some other output if the file wasn't updated (because it already existed)

Seems reasonable to me!

**Comment by jonjohnsonjr** [comment]
Once we update dependencies, we should be able to merge a fix for this.
