### ISSUE TITLE
Continuing to struggle with ko v0.5.0  using ko:// and --preserve-import-paths

### ISSUE THREAD

**Issue by bobcatfish** [google/ko#164]
I thought that #163 had fixed our issue https://github.com/tektoncd/plumbing/issues/370 but it looks like I didn't actually try it properly :(

When I try to run ko for tektoncd/pipelines, I get this error:

```
2020/05/06 08:48:37 error processing import paths in "config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: christiewilson-catfactory/ko://github.com/tektoncd/pipeline/cmd/webhook
```

I have tekton pipelines checked out at:
https://github.com/tektoncd/pipeline/commit/42804258d81f359e00156237fefd9252184bc52f

From the root folder (pipeline) I run:

```
ko resolve --preserve-import-paths -t v20200504-7bbc7ebf3b -f config/
```

When I replace `--preserve-import-paths` with `-B` it works.

I've tried both of these ways to install the version of ko that should have the fix:

```
# installing v0.5.0
go get github.com/google/ko/cmd/ko@v0.5.0

# trying to be sure i get exactly the commit with the fix
go get github.com/google/ko/cmd/ko@ea2beac5751c62af0c019f60145c4bc26e094081
```

**Comment by bobcatfish** [comment]
But apparently if i do `go get github.com/google/ko/cmd/ko`, then the command works. I am so confused.

**Comment by mattmoor** [comment]
@ImJasonH Do you think it's worth cutting 0.5.1 just to rule out our futzing with 0.5.0?

**Comment by ImJasonH** [comment]
Yeah that sounds fine. Maybe the old 0.5 got cached somewhere?

**Comment by mattmoor** [comment]
alright, I'll try that now

**Comment by mattmoor** [comment]
https://github.com/google/ko/actions/runs/97223277

**Comment by bobcatfish** [comment]
Some relevant docs on "go get" behavior that may be at the root of why this isnt always behaving the same way: https://golang.org/cmd/go/#hdr-Legacy_GOPATH_go_get

**Comment by ImJasonH** [comment]
@mattmoor the goreleaser task failed with 

```
   ⨯ release failed after 186.36s error=github/gitlab/gitea releases: failed to publish artifacts: failed to upload ko_0.5.0_Linux_x86_64.tar.gz after 1 tries: POST https://uploads.github.com/repos/google/ko/releases/26149970/assets?name=ko_0.5.0_Linux_x86_64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

(it thinks it's trying to release v0.5.0 again?)

But the tag and [GH release for 0.5.1 exists](https://github.com/google/ko/releases/tag/v0.5.1). Is there anything else to do here, besides just close this bug?

It's blocking Tekton's next attempt to `ko://`-prefix everything: https://github.com/tektoncd/pipeline/pull/2675

**Comment by mattmoor** [comment]
That's odd, the release is empty.  I never tagged 0.5.2, which IIRC has a single additional change that been working for me.  We can give that a shot?

**Comment by mattmoor** [comment]
@ImJasonH @bobcatfish @afrittoli here is what we're using in our Prow config:
https://github.com/knative/test-infra/blob/master/images/prow-tests/Dockerfile#L67

(thanks to @chizg for the pointer)
