### ISSUE TITLE
ko resolve with `--push=false` panics

### ISSUE THREAD

**Issue by vdemeester** [google/ko#166]
`ko resolve --push=false -f config` panics

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1344755]

goroutine 134 [running]:
github.com/google/ko/pkg/resolve.ImageReferences.func1(0x0, 0x0)
	/tmp/tmp.UsUiwYBfML/src/github.com/google/ko/pkg/resolve/resolve.go:66 +0x115
github.com/google/ko/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001d5140, 0xc00045e190)
	/tmp/tmp.UsUiwYBfML/src/github.com/google/ko/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by github.com/google/ko/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/tmp/tmp.UsUiwYBfML/src/github.com/google/ko/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
make: *** [Makefile:47: build] Error 2
```

/cc @mattmoor

**Comment by mattmoor** [comment]
I didn't even know `--push=false` existed!  I'll pull up that line and see what it might be

**Comment by mattmoor** [comment]
I'm guessing it is the `digest.String()` because of the `--push=false`?

```
			sm.Store(ref, digest.String())
```

**Comment by mattmoor** [comment]
What publisher are you using?  A real registry?

**Comment by mattmoor** [comment]
Also if you could share accurate `ko` version info it'd be helpful to know I'm looking at the right lines 😅

**Comment by vdemeester** [comment]
@mattmoor I am using `gcr`. But not pushing means it doesn't get a digest from what I assume, hence the panic.
It is using `ko@master` :wink:

**Comment by mattmoor** [comment]
Yeah, it looks like if you pass `--push=false` and nothing else (e.g. OCI, tarball) then the multi-publisher with no inner publishers return nil:
https://github.com/google/ko/blob/ab4ca8ec17fc10541f2ddb1ef3b4118524a39079/pkg/publish/multi.go#L35-L45

**Comment by mattmoor** [comment]
This shouldn't be new, so hopefully it's not breaking anything.  I'm curious what the use case is, since it doesn't seem like `resolve` has any reasonable value to use for the reference in the yaml.

Perhaps you are just looking for a better error, which is perfectly reasonable, I just want to make sure there isn't anything else.

**Comment by vdemeester** [comment]
@mattmoor oh I could use `--oci-layout-path` and it would probably work ? (let me try that)
So my use case is to use `ko` to just to the `go build` :stuck_out_tongue_closed_eyes: but not pushing the images

**Comment by vdemeester** [comment]
Alright, it works fine with `--oci-layout-path`. Maybe we can enhance the error indeed and error out quickly (as soon as `--push=false`  without `--oci-layout-path`)

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/216
