### ISSUE TITLE
List of packages in image

### ISSUE THREAD

**Issue by jicowan** [google/ko#169]
Is there a way to get a list of the OS packages that are installed when ko creates an image?  I'm looking for the package name and version.

**Comment by mattmoor** [comment]
Do you mean Go packages, or do you mean system packages?

For the latter, we (by default) base on distroless, which does have some mechanism by which it reports this.  @dlorenc may recall more than me here.

For the former, not that I'm aware of.  Depending on what you need (e.g. licenses), we have some places downstream where we solve similar problems.
