### ISSUE TITLE
Watch does not work with `ko://`

### ISSUE THREAD

**Issue by pauldemarco** [google/ko#170]
Steps to reproduce:
1. Be in the root directory of a Go mod project. e.g. `module myproject.com`
2. Verify you can successfully `ko apply -L -f build/chart.yaml`
3. Attempt to add the `-W` flag, like so: `ko apply -L -W -f build/chart.yaml`
4. Note the following error:
```
2020/05/28 13:25:01 watching dependencies: adding importpath to dep graph: package ko:/myproject.com/cmd/write-model is not in GOROOT (/usr/local/go/src/ko:/myproject.com/cmd/write-model)
```

**Comment by pauldemarco** [comment]
I should also note that if I remove the use of `ko://` in the manifests the watch works great.

**Comment by mattmoor** [comment]
Your example has `ko:/` (single `/`) is that the bug?
