### ISSUE TITLE
Integration tests for go module support

### ISSUE THREAD

**Issue by Cynocracy** [google/ko#171]
ko, when run from within the GOPATH, uses GOPATH mode for resolving images even when environment variables instruct otherwise.

ko version 0.5.1

**Comment by Cynocracy** [comment]
One caveat here: I have 2 machines with this setup and they're behaving differently :( One seems to do fine with the module type ko:// references to vendor. The other does not. I'll have to take a look and see if ko has debugging tips anywhere, I'd love to figure out this mystery :)

**Comment by Cynocracy** [comment]
Thoughts on changing to using https://golang.org/pkg/go/build/ from exec to see if that helps resolve inconsistencies?

**Comment by Cynocracy** [comment]
In slack I got a "sure, why not?" So I'm going to play around with that.

/assign Cynocracy

**Comment by Cynocracy** [comment]
Oh, this repo isn't as fancy. I'll do it myself :P

**Comment by Cynocracy** [comment]
No luck, but please consider it assigned.

**Comment by Cynocracy** [comment]
This /may/ have been due to a bug in our setup, but we're investigating a bit more now that we got our internal repo into a good state. That should help us understand a bit better why this is occurring (and play around with fixes :)

**Comment by Cynocracy** [comment]
OK, here's my attempt at repro.

Setup
1. Add a tools.go file to ko's root, and import 'github.com/go-training/helloworld'
2. `go mod vendor && go mod tidy`
3. Modify vendor to change message output
4. Make sure you are in the GOPATH (where you might fallback to GOPATH mode) and you run `go get -d githu`b.com/go-training/helloworld`

Scenarios:
a. GO111MODULE=on GOFLAGS="-mod=vendor" should always output the changed text
b. GO111MODULE=auto GOFLAGS="-mod=vendor" should output the changed text iff in the module path, otherwise the original text.
i.  In the module root
ii. Outside module root
c. GO111MODULE=off should output the original text.
d. GO111MODULE=on should fail outside a module.

Results:
a. GO111MODULE="on" GOFLAGS="-mod=vendor" ko publish github.com/go-training/helloworld

docker run result
Hello World TEST!!

b. 
i.
Hello World TEST!!
  
ii.
Hello World!!

c. 
Hello World!!

d.
go: cannot find main module; see 'go help modules'


So: WAI :+1: Most likely the issues I was seeing were related to our own infra around ko and not ko itself.

Any objections to me adding something similar as an integration test?

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/179
