### ISSUE TITLE
[Request] Will ko be based on Dockerfile to build image?

### ISSUE THREAD

**Issue by zzxwill** [google/ko#174]
In some situation,  docker image won't be easily built just from Go modules with `import paths`. A complicate `Dockerfile` like [this](https://github.com/crossplane/addon-oam-kubernetes-local/blob/master/Dockerfile) needs to be used for image build. While ko is so good at building and pulling image behind the console, it would save a lot of efforts if ko will also consider building image  based on `Dockerfile`.

So will `Dockerfile` be an option? Thanks.

**Comment by jonjohnsonjr** [comment]
We've casually discussed adding support for other kinds of builds beyond just golang: https://twitter.com/mattomata/status/1253165136501596160
https://github.com/tektoncd/pipeline/issues/2493#issuecomment-619403530
https://github.com/google/ko/pull/104#issuecomment-562688793

I think we're open to the idea, but I'd like to see the idea fleshed out.
