### ISSUE TITLE
Release 0.5.1 with pre-built binaries

### ISSUE THREAD

**Issue by odsod** [google/ko#183]
Would be great to have prebuilt binaries with https://github.com/google/ko/commit/ab4ca8ec17fc10541f2ddb1ef3b4118524a39079 included!

**Comment by jonjohnsonjr** [comment]
There was already a v0.5.1 tag for some reason, so I pushed v0.5.2 with that fix included 👍

**Comment by odsod** [comment]
Thank you @jonjohnsonjr :raised_hands:
