### ISSUE TITLE
Generate markdown docs for ko commands

### ISSUE THREAD

**Issue by ImJasonH** [google/ko#20]
See https://github.com/google/go-containerregistry/pull/115

Also ensure that generated docs stay up-to-date ([example](https://github.com/google/go-containerregistry/blob/80cc55a02b4234cd9424777ae149059ed1119828/.travis.yml#L25))

**Comment by joshuabezaleel** [comment]
Hi @ImJasonH , if it's okay with you I would like to ask a question regarding this issue.

I saw your PR at the google/go-containerregistry regarding generating the docs for the Crane CLI commands where you refactor the design to make Crane into its own package so that the Root top-level Cobra command can be exported and then used as crane.Root for the doc.GenMarkDownTree parameter. 

I have taken a look at the codebase and since we put everything including the Root top-level Cobra command at the package main, do you have any recommendation on how to get the value of [cmds](https://github.com/google/ko/blob/master/cmd/ko/main.go#L25)? Would it be better to make the Ko commands to its own package so that it can be exported and the top-level command can be used or just make another .go file let's say help.go at the same level of the main.go file?

Thank you very much! Have a great day :slightly_smiling_face:

**Comment by ImJasonH** [comment]
Hey @joshuabezaleel thanks for your interest!

I don't think we necessarily need to move ko's commands into pkg, we could just keep them in cmd for now, to minimize the impact of your potential change.

The only thing we have to do is make `cmds` an exported package-level var so that the command that generates help docs can see it to call `GetMarkDownTree` on it.

So, if we refactor `cmd/ko/main.go` to this:

```go
// Root is the parent command to which all subcommands are added.
var Root = &cobra.Command{
        Use:   "ko",
        Short: "Rapidly iterate with Go, Containers, and Kubernetes.",
        Run:   func(cmd *cobra.Command, args []string) { cmd.Help() },
}

func init() { addKubeCommands(Root) }

func main() {
        if err := Root.Execute(); err != nil {
                log.Fatalf("error during command execution: %v", err)
        }
}
```

Then inside `cmd/gendoc/main.go` (or whatever we call it) we can do this:

```go
import "github.com/google/ko/cmd/ko"

...

if err := doc.GenMarkdownTree(ko.Root, dir); err != nil {
	log.Fatalln(err)
}
```

Some other minor tasks we should include in this work:

* add generated .md files to `.gitattributes` so that GitHub knows they're generated ([example](https://github.com/google/go-containerregistry/pull/115/files#diff-fc723d30b02a4cca7a534518111c1a66))
* add a test to .travis.yml to check that generated docs are up-to-date ([example](https://github.com/google/go-containerregistry/blob/1d38b9cfdb9d294aca666bf0c1c0bcade771e8c9/.travis.yml#L24-L25))

**Comment by joshuabezaleel** [comment]
> Hey @joshuabezaleel thanks for your interest!
> 
> I don't think we necessarily need to move ko's commands into pkg, we could just keep them in cmd for now, to minimize the impact of your potential change.
> 
> The only thing we have to do is make `cmds` an exported package-level var so that the command that generates help docs can see it to call `GetMarkDownTree` on it.
> 
> So, if we refactor `cmd/ko/main.go` to this:
> 
> ```go
> // Root is the parent command to which all subcommands are added.
> var Root = &cobra.Command{
>         Use:   "ko",
>         Short: "Rapidly iterate with Go, Containers, and Kubernetes.",
>         Run:   func(cmd *cobra.Command, args []string) { cmd.Help() },
> }
> 
> func init() { addKubeCommands(Root) }
> 
> func main() {
>         if err := Root.Execute(); err != nil {
>                 log.Fatalf("error during command execution: %v", err)
>         }
> }
> ```
> 
> Then inside `cmd/gendoc/main.go` (or whatever we call it) we can do this:
> 
> ```go
> import "github.com/google/ko/cmd/ko"
> 
> ...
> 
> if err := doc.GenMarkdownTree(ko.Root, dir); err != nil {
> 	log.Fatalln(err)
> }
> ```
> 
> Some other minor tasks we should include in this work:
> 
>     * add generated .md files to `.gitattributes` so that GitHub knows they're generated ([example](https://github.com/google/go-containerregistry/pull/115/files#diff-fc723d30b02a4cca7a534518111c1a66))
> 
>     * add a test to .travis.yml to check that generated docs are up-to-date ([example](https://github.com/google/go-containerregistry/blob/1d38b9cfdb9d294aca666bf0c1c0bcade771e8c9/.travis.yml#L24-L25))

Hey @ImJasonH , since ko's commands doesn't have its own package and reside in package `main`, I got an error of `import "github.com/google/ko/cmd/ko" is a program, not an importable package`. Is this going to be okay when we run the docs generation?

**Comment by ImJasonH** [comment]
That's a good point, I forgot you can't import from a `package main`.

In that case we need to move at least the `Root` command to `pkg/ko`, but we can still keep `addKubeCommands` (in a `func init`) in `cmd/ko` for now, unless that doesn't work for some reason or unless we just don't like it.

That seems like the easiest way to accomplish this without having to move everything into `pkg`.

**Comment by joshuabezaleel** [comment]
Since I am really new to Go and furthermore ko, I am really sorry if I got many things wrong here and there. Looking forward to your review, @ImJasonH ! Thank you very much! :slightly_smiling_face:
