### ISSUE TITLE
ko support the specified package name as image name

### ISSUE THREAD

**Issue by qmloong** [google/ko#206]
I will get image `<DOCKER_REMO>/net-istio/controller` when I run this cmd
`KO_DOCKER_REPO=<DOCKER_REMO>/net-istio ko publish -B -t v0.16.1  ./cmd/controller/ `

but sometimes I want to rename docker repo image name, like `ccr.ccs.tencentyun.com/net-istio/networking-istio-controller`.

may ko support  the `-o networking-istio-controller` options?

**Comment by jonjohnsonjr** [comment]
With https://github.com/google/ko/pull/234 merged, you should be able to do this:

```
KO_DOCKER_REPO="<registry>/networking-istio-controller" ko publish --bare ./cmd/controller/
```
