### ISSUE TITLE
`ko version` to report build/version information

### ISSUE THREAD

**Issue by ImJasonH** [google/ko#21]
Using https://github.com/ahmetb/govvv

**Comment by cezkuj** [comment]
I would like to take care of it. Could you advise on activities needed besides adding 'version' command? govvv changes build process (as you don't use go build directly anymore) and I don't see any build wrapper (Makefile/scripts etc.) to hide that. Same problem with using package, users 'go getting' ko wouldn't have it working.

**Comment by ImJasonH** [comment]
Thanks for your interest @cezkuj !

We don't currently have an official release process or any release scripts, which is probably a prerequisite for this.

For users can install via `go get` we can have `go version` return the commit hash that's checked out (by inspecting `$GOPATH/src/github.com/google/ko/.git/refs/heads/master` (or else whatever is `HEAD`) at runtime, if the const value isn't provided.

FWIW, I also found [an alternative approach](https://stackoverflow.com/questions/11354518/golang-application-auto-build-versioning) to `govvv` which is to use `-ldflags` to set the value of a package-level const at build-time.

**Comment by cezkuj** [comment]
As far as I see, govvv also uses -ldflags approach. I feel like that's most common way to get build info.  Not sure if it is worth to have hard dependency on other project to reduce few less lines here and there - your call.
Shall I add Makefile/bash/bazel/anything else to wrap building and releasing process within that issue?
Or just add code for version command?

**Comment by ImJasonH** [comment]
Right you are. I don't have a strong opinion about taking a dependency on `govvv`, it seems pretty straightforward and if we ever needed to stop using it we could.

I think if you add a release script that populates consts which `go version` prints that'd be sufficient. We'll tag a release after that and document how to get an official release where `go version` prints something other than the commit hash.

**Comment by cezkuj** [comment]
Overall I agree, but one thing is a bit unclear to me, what do you mean by 
> go version prints something other than the commit hash.
I don't see any way to get it from go version, do you mean git rev-parse (or some equivalents)?

**Comment by ImJasonH** [comment]
Yeah, using `git rev-parse` would work, basically:

```
 // provided by govvv
var Version, BuildDate string

func goVersion() {
  if Version == "" {
    hash := gitRevParseHead() // output of `git rev-parse HEAD`
    fmt.Println("version (go get):, hash)
  } else {
    fmt.Println("version:", Version)
  }
}
```

Let me know if you had something else in mind. I don't have a strong opinion about what the output should look like. Users have only actually asked for a way to get the released version string from the command, we could skip the fallback for simplicity for now as well.

**Comment by cezkuj** [comment]
Ok, understood. Will prepare something like that + script to wrap releasing.
Thanks for answering!

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/25 and https://github.com/google/ko/pull/81
