### ISSUE TITLE
ko resolve segfaults when push=false

### ISSUE THREAD

**Issue by ian-mi** [google/ko#215]
When push=false there are no publishers and multiPublisher.Publish will return a nil name.Reference causing a segfault:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1610af5]

goroutine 13 [running]:
github.com/google/ko/pkg/resolve.ImageReferences.func1(0x1, 0x665a99)
        /usr/local/google/home/ianmi/go/pkg/mod/github.com/google/ko@v0.6.0/pkg/resolve/resolve.go:66 +0x115
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000362a80, 0xc0000b6230)
        /usr/local/google/home/ianmi/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /usr/local/google/home/ianmi/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66

**Comment by ImJasonH** [comment]
What command were you running?

I tried with `ko publish <importpath> --push=false` and it succeeded (though it logged the final line `<nil>`...)

`ko apply` did fail with the stacktrace though.

**Comment by jonjohnsonjr** [comment]
https://github.com/google/ko/issues/166

**Comment by ImJasonH** [comment]
WIP at https://github.com/google/ko/compare/master...ImJasonH:multi-panic

It gets around this by injecting `not-published@sha256...`

**Comment by jonjohnsonjr** [comment]
As mentioned in the other bug, there doesn't seem to be any utility in just setting push=false without any other publisher. We should just return a descriptive error here.

@ian-mi does that sound right or are you interested in some kind of NOP publisher as a dry run?

**Comment by ian-mi** [comment]
I think it'd be great to have a dry run mode for testing purposes as that's
how I was attempting to use the push flag. I can open a separate feature
request for that, however.

**Comment by ImJasonH** [comment]
Updated the PR to do a nop push. This ignores `-P` or `-B` flags, and always uses `-P` behavior.
