### ISSUE TITLE
ko uses "go" as default GOROOT, causing build errors

### ISSUE THREAD

**Issue by antoineco** [google/ko#218]
### Description

`ko` uses `"go"` as GOROOT when GOROOT is not exported in the environment, instead of defaulting to `$(go env GOROOT)`. This prevents builds from happening.

In the previous version, the error message was quite explicit: `"go: cannot find GOROOT directory: go"`.

Now, in 0.6.0, the error is much more ambiguous: `importpath "ko://knative.dev/serving/cmd/controller" is not supported`.

### ko version

```
$ ko  version
0.6.0
```

### How to reproduce

Example, inside https://github.com/knative/serving/
```console
$ printenv GOROOT  # empty
```
```console
$ ko publish -L ./cmd/controller  # failure
2020/10/07 12:41:33 failed to publish images: importpath "ko://knative.dev/serving/cmd/controller" is not supported
```
```console
$ export GOROOT="$(go env GOROOT)"
```
```console
$ printenv GOROOT
/usr/local/go
```
```console
$ ko publish -L ./cmd/controller  # success
2020/10/07 12:45:13 Using base gcr.io/distroless/static:nonroot for knative.dev/serving/cmd/controller
2020/10/07 12:45:15 Building knative.dev/serving/cmd/controller for linux/amd64
[...]
```

### Temporary workaround

Add this line to your `.*shrc` file:

```sh
export GOROOT="${GOROOT:-$(go env GOROOT)}"
```

**Comment by mattmoor** [comment]
I think @scothis has an open issue for this, and I think @jonjohnsonjr has the most context on this issue.

**Comment by scothis** [comment]
@mattmoor https://github.com/google/ko/issues/106

**Comment by antoineco** [comment]
@scothis do I understand correctly that `ko` just needs to be rebuilt (e.g. via `go get`) for GOROOT to default to the expected value?

**Comment by mattmoor** [comment]
Unfortunately `go get` ignores `replace` directives in `go.mod`, so I'd recommend `go install`.

**Comment by jonjohnsonjr** [comment]
I believe this is resolved by https://github.com/google/ko/pull/303

Please let me know if that is not the case.

**Comment by xtreme-sameer-vohra** [comment]
> I believe this is resolved by #303
> 
> Please let me know if that is not the case.

I believe I ran into the same issue using v0.7.2 and using the current HEAD with the fix solved it.

**Comment by sebgoa** [comment]
Yes, this is still an issue in 0.7.0

**Comment by jonjohnsonjr** [comment]
@sebgoa as of v0.8.0, this now prints a warning, does the "right" thing, and includes instructions for making that warning go away (by setting `GOROOT` explicitly).

My intention is to remove the need for this warning before cutting v0.9.0, as described in https://github.com/google/ko/issues/305

If you're still having issues in v0.8.0, let me know.

**Comment by sebgoa** [comment]
I realised that I ran into this because the Installation section in the README makes you install 0.7.0 binary, hence I did not get the warning.
