### ISSUE TITLE
ko resolve not working with limited network access to some source repo in vendor mode

### ISSUE THREAD

**Issue by cathyzhyi** [google/ko#228]
The problem is found in a container environment with limited network access to certain repos. 
The reason is because [this line](https://github.com/google/ko/blob/d9cc0ca9ea6754cb57e2e63a5a1c88f0a43bd81c/pkg/build/gobuild.go#L114) executes `go list -mod=readonly -json -m all` 
unconditionally. 

**What's expected**: 
`ko resolve` should give user the option to avoid doing `go list -mod=readonly -json -m all`
 in vendor mode when network access is limited.

**Comment by ian-mi** [comment]
Ideally we'd have the option to run go list -mod=vendor instead to force ko to resolve paths using only vendored modules.

**Comment by jonjohnsonjr** [comment]
If you have a clever idea for how to implement this in a backwards compatible way, or a proposed API change to do this, I'm all ears.

I'd be fine with either an undocumented flag or environment variable that just changes this flag in this invocation to unblock y'all until a better solution comes forward.

**Comment by ian-mi** [comment]
Thanks Jon, we were able to workaround the issue by allowing access to the source repos so please don't treat this as urgent.

A simple fix might be to call go list with -mod=vendor whenever a vendor directory is present. This matches the go behavior of defaulting to -mod=vendor which the use of -mod=readonly overrides.

Another idea is to add a --vendor-only flag which restricts ko to deploying images from vendored source. When enabled go commands including go list would use -mod=vendor. I'm not sure if other restrictions would be needed to provide this functionality.

**Comment by jonjohnsonjr** [comment]
I see -- will probably want to dig through the `go` tool's code and copy their heuristic (or maybe they export it).

Glad you're not blocked!
