### ISSUE TITLE
ko resolve say nothing if go import path not correct

### ISSUE THREAD

**Issue by vincent-pli** [google/ko#23]
I try to use ko resolve to build and containerize the golang code.
Firstly, when I run `ko resolve -f xxx.yaml > release.yaml`, there is nothing print out and the command complete, only stuff generated is the release.yaml, no compile, no docker image rendered.

After several hours struggle, I find the golang import path in xxx.yaml is wrong by typo!
I hope the `ko resolve` could say something which can hint me, thanks.

**Comment by ImJasonH** [comment]
This is another example of the issue described in https://github.com/google/ko/issues/9 -- watch there for any updates, though I don't think we've decided on any definitive answer to this. :disappointed:
