### ISSUE TITLE
set `GOARM` for older arm variants

### ISSUE THREAD

**Issue by mattmoor** [google/ko#235]
Prior to aarch64 to build for arm variants you needed to set `GOARCH=arm GOARM=v6` or whatnot.

I don't believe we currently set this, although I believe it appears in the platform info in the manifest list.

cc @jonjohnsonjr 

I noticed this building a `ko` image on `golang`, which has many many variants.

**Comment by jonjohnsonjr** [comment]
From https://golang.org/cmd/go/: 
```
For GOARCH=arm, the ARM architecture for which to compile.
	Valid values are 5, 6, 7.
```
