### ISSUE TITLE
ko publish fails with local registry

### ISSUE THREAD

**Issue by nicks** [google/ko#237]
To test Ko, I tried running a registry at localhost:45197 and ran:

```
$ KO_DOCKER_REPO=localhost:45197 ko publish github.com/mattmoor/warm-image/cmd/sleeper
2020/11/03 15:46:43 No matching credentials were found, falling back on anonymous
2020/11/03 15:46:43 failed to publish images: importpath "ko://github.com/mattmoor/warm-image/cmd/sleeper" is not supported
```

I'm not sure what this error message means...this is the exact `ko publish` command in https://github.com/google/ko#ko-publish . Am i missing something?

```
$ ko version
v0.6.0
```

**Comment by jonjohnsonjr** [comment]
https://github.com/google/ko/pull/233 is meant to address exactly this but isn't in a tagged release yet...

@ImJasonH

**Comment by nicks** [comment]
hmmm...I built Ko from main to pull in Jason's change, and got this error:

```
$ KO_DOCKER_REPO=localhost:45197 ko publish github.com/mattmoor/warm-image/cmd/sleeper
2020/11/03 16:05:50 No matching credentials were found, falling back on anonymous
2020/11/03 16:05:50 failed to publish images: importpath "ko://github.com/mattmoor/warm-image/cmd/sleeper" is not supported: open /home/nick/src/ko/vendor/github.com/mattmoor/warm-image/cmd/sleeper: no such file or directory
```

so...better? but seems like it needs me to have the code checked out locally first to build it?

**Comment by jonjohnsonjr** [comment]
> but seems like it needs me to have the code checked out locally first to build it?

Possibly. I think prior to go modules this just worked (go would `go get` anything that was missing), but I'm not 100% sure.
