### ISSUE TITLE
`ko resolve` removed --strict flag

### ISSUE THREAD

**Issue by sbawaska** [google/ko#240]
In 0.6.1, the --strict flag on `ko resolve` was removed. This flag was present in 0.6.0. 
I did not expect this flag to get removed in a patch version.

**Comment by jonjohnsonjr** [comment]
Ah, yeah, sorry this was my mistake with tired eyes this morning.

I believe just reverting https://github.com/google/ko/commit/d7b989a9dffe912e3b4effa427628ebe08a40902 and tagging that as v0.6.2 would fix this?

**Comment by mattmoor** [comment]
@sbawaska yeah, I poked him about this but the damage was already done and historically we've broken things just as badly by removing tags, so I'm a bit gun shy on fixing this.  Ping me if you need any help resolving this.

**Comment by sbawaska** [comment]
no worries, I have worked around this issue.

**Comment by jonjohnsonjr** [comment]
Just cut https://github.com/google/ko/releases/tag/v0.6.2

Once https://github.com/google/ko/actions/runs/346392053 finishes, hopefully you can update and unbreak. Sorry for the inconvenience!
