### ISSUE TITLE
KO_CONFIG_PATH is confusing

### ISSUE THREAD

**Issue by benmoss** [google/ko#245]
I have been bitten twice by this, so I'm gonna file a bug now :)

If you set `KO_CONFIG_PATH` to a filepath to the `.ko.yaml` file, ko will silently ignore this setting. It seems really unintuitive that it points to the **directory** with a `.ko.yaml` in it, rather than just pointing to the file itself. Either way it should error if `KO_CONFIG_PATH` is set but not readable.

**Comment by ImJasonH** [comment]
+1, we can do better.

The code is at https://github.com/google/ko/blob/master/pkg/commands/config.go and it leans on viper to parse and interpret the config file, which apparently swallows not-foundiness.

We could check whether the env var, if set, can be used to find the file, and exit if it can't.

**Comment by jonjohnsonjr** [comment]
Something stupid like:

```go
if filepath.Base(override) == ".ko.yaml" {
  override = filepath.Dir(override)
}
```

Might work? though this assumes you haven't put a `.ko.yaml` file inside a `ko.yaml/` directory....

Also if you're overriding this, maybe we should document https://github.com/google/ko/pull/131 better.

**Comment by dprotaso** [comment]
Can we re-open this and freeze the issue
