### ISSUE TITLE
Feature request - option to publish N architectures

### ISSUE THREAD

**Issue by alexellis** [google/ko#253]
I tend to build for armhf, arm64 and Intel, so could use an option to give the three architectures. When @mattmoor gave me a demo earlier today (very impressed with the workflow) - it seemed like I could only give one architecture or the predefined list in all?

**Comment by mattmoor** [comment]
cc @jonjohnsonjr 

Yeah, right now there is only `--platform=all` and `--platform=os/arch`

**Comment by jonjohnsonjr** [comment]
> or the predefined list in all

This isn't actually predefined, it's derived from the base image. The default base image happens to be `gcr.io/distroless/static:nonroot`:

```
$ crane manifest gcr.io/distroless/static:nonroot
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 426,
         "digest": "sha256:572620cc4108b51662307290f1c9c6cd4cb6b42eedc68d218c7ba50e709fbd3e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 426,
         "digest": "sha256:c367236866f91e24bb793a2e764918b9fd1bef8d4a4e292bc5f184f02318b216",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 426,
         "digest": "sha256:7b1b2d30014678efbfc19980b924f134cfcbe38bdac4a33a5e2d8d15dc12c3e6",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 426,
         "digest": "sha256:e83342ea9d8278ecee63d0b2c867515a03d21389e1c1b9227a924fb1d9bfd9f6",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 426,
         "digest": "sha256:796ff193c9ae25911401d4e687b9646ad81e4bec028876073cc5dcfbed694c14",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

So in some sense it is predefined, but you can override it by supplying a different base image. I do agree that your FR is useful, though, as I don't care about most of those architectures :)

**Comment by jonjohnsonjr** [comment]
@alexellis want to give the linked PR a spin?

**Comment by jonjohnsonjr** [comment]
Notably, that PR acts as a filter on the platforms that are available in the base image. We won't be able to synthesize a base image out of nothing.

Matt suggested a magic base image "scratch" that would be completely empty. In theory, we could produce any (valid) platform that go supports: https://github.com/google/ko/issues/207

But then you run into all the issues that come with a completely scratch base image.
