### ISSUE TITLE
Idea: use buildid to avoid go link time

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#265]
Somewhat related to https://github.com/google/ko/issues/264

`go build` doesn't cache linked executables because they're too large, but if the binary exists at the target destination and has the right buildid, it can skip the build: https://github.com/golang/go/issues/25416#issuecomment-389495625

So even though we benefit from many cached build targets, we still pay the link price every time because we `-o` to a tempdir and delete the binary after we push.

```
# Slow, but mostly cached.
$ time go build ./cmd/ko/

real	0m3.390s
user	0m3.709s
sys	0m0.899s

# Very fast
$ time go build ./cmd/ko/

real	0m0.762s
user	0m0.861s
sys	0m0.452s

# Slow again.
$ rm ko && time go build ./cmd/ko/

real	0m3.267s
user	0m3.720s
sys	0m0.717s
```

You can look at the buildid for an existing binary:

```
$ go tool buildid ko 
XAPd-KEoMLeM6geLs5WA/Hi3fP9fBKQdHKuAUx9Hq/BzVlEW6rvXk7RD6j8Dvy/pq1XTmuPaiGmLIF0Lzx8
```

You can even ask `go build` to print stuff but not execute it, which includes the buildid:

```
$ time go build -n ./cmd/ko/ 2>&1 | grep buildid
/usr/local/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=XAPd-KEoMLeM6geLs5WA/Hi3fP9fBKQdHKuAUx9Hq/BzVlEW6rvXk7RD6j8Dvy/XAPd-KEoMLeM6geLs5WA -extld=gcc /home/jonjohnson/.cache/go-build/f8/f8582a76a43a819c3314066cdbbbe2a8b41d2ef37335ae9fb4fb558ef26958fb-d
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b001/exe/a.out # internal

real	0m0.839s
user	0m0.873s
sys	0m0.454s
```

I don't know if there's a better interface for asking what the buildid of the thing you want to build is, but worst case we could parse this out of the output of `go build -n`. I think we wouldn't even have to pay the cost of doing this check and wasting time, because we could just turn around and exec this output to do what `go build` would have done anyway.

This feels like a _bit_ of a hack, but we could save several seconds on every build (if we don't have to actually rebuild...).

Perhaps we could maintain a separate data structure mapping buildid to diffid, or just use buildid for the cache key in https://github.com/google/ko/issues/264.

If we can figure out the buildid without actually linking the binary, then we can figure out the diffid, digest, and size without linking, and (assuming the registry has the layer already), we can avoid gzipping or pushing the binary layer altogether.

Need to talk to somebody who knows more about `go build` to see if this is a terrible idea...

For `ko`, this would save ~2-3 seconds per binary from my testing. Combine that with the gzip and sha256 savings, and it's more like 5-6 seconds for each cache hit, and very little penalty for a miss. At that point I think we're limited by the upload path, for which I have a few ideas.

cc @mattmoor @ImJasonH wdyt

**Comment by ImJasonH** [comment]
Would it make sense to just `go build -o /tmp/ko` instead of building into a new temp dir each time? That really seems like the ultimate cause, `go build` can't tell we've already built it.

That way we only depend on `go build`'s built-in smarts from "outside", and don't try to simulate its smarts ourselves. This means that future changes/breakages to those smarts won't break us unexpectedly, and future improved smarts might benefit us too.

**Comment by mattmoor** [comment]
`/tmp/ko` won't work for concurrent builds, but I am 👍 on fixing this.  The use of temp was just a naive way of getting a binary in a concurrent-safe way that was in an obviously clean-up safe place.

**Comment by jonjohnsonjr** [comment]
We could do `/tmp/ko/${IMPORT_PATH}/${sha256(cmd.Path + cmd.Args + cmd.Env)}`?

Arguably `${IMPORT_PATH}` isn't necessary because you can just `go version -m $BINARY` to figure out what it is, but it feels nice to have some idea for what you're looking at?

**Comment by ImJasonH** [comment]
I still want this.

/remove-lifecycle stale

**Comment by mattmoor** [comment]
Is this done?
