### ISSUE TITLE
Add ko to homebrew?

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#296]
My limited understanding of homebrew is that you can either add a formula to homebrew/core or maintain a tap.

It seems like less over head if we can get into core (we don't have to maintain a separate repo), but from [their guidelines](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff):

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
> 
> We frown on authors submitting their own work unless it is very popular.

I'm not sure if `ko` is "very popular", but it seems like it's more likely to be accepted if _someone else_ submits it...

Also, we need a homepage.

**Comment by jonjohnsonjr** [comment]
cc @n3wscott

**Comment by chenrui333** [comment]
I can help with this issue.
