### ISSUE TITLE
Publish a `ko` image

### ISSUE THREAD

**Issue by bobcatfish** [google/ko#3]
In https://github.com/knative/build-pipeline/issues/529 and https://github.com/knative/build-pipeline/issues/528 I'm adding dogfooding CI/CD logic for publishing [tekton pipelines](https://github.com/knative/build-pipeline) images and yamls. 

This means I want to create a [Task step or steps](https://github.com/knative/build-pipeline/blob/master/docs/tasks.md#steps) which invoke `ko`, since this is how we currently build and publish our images (via a bash script).

To do this, I need a container with `ko` installed. For now I'll have a first step that installs `ko`, but would be great if [a `ko` image could be published and available for folks to use](https://github.com/google/go-containerregistry/blob/master/cloudbuild.yaml).

(Looks like #358 might be related but I'm not sure?)

**Comment by 06kellyjac** [comment]
I'd still like an official `ko` image or at least a reason why not to have one.

**Comment by jonjohnsonjr** [comment]
I'm not opposed to having one, but credentials are tricky.

**Comment by bobcatfish** [comment]
@jonjohnsonjr [the way we solve this in our tekton release infra is not super great](https://github.com/tektoncd/pipeline/blob/d48fbd73a3786a37dcd7bbbf2be6dc713caa785d/tekton/publish.yaml#L102-L107)

[we build an image with both ko and gcloud (and kubectl)](https://github.com/tektoncd/plumbing/blob/master/tekton/images/ko-gcloud/Dockerfile) and explicitly call out to gcloud to activate a service account and configure docker:

```bash
      # Activate service account
      gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
      # Setup docker-auth
      gcloud auth configure-docker
```

**Comment by jonjohnsonjr** [comment]
I was looking into how minikube configures credentials for an unrelated issue and noticed that they use this project: https://github.com/upmc-enterprises/registry-creds/

Possibly we could do something similar?

Also, for `crane`, somebody mentioned they were just piggybacking off of the kaniko image: https://github.com/google/go-containerregistry/issues/731#issuecomment-705154322

**Comment by jonjohnsonjr** [comment]
To sketch out what I'd probably want to do for this:

1. Create a `docker-credential-k8schain` binary. This would speak the docker credential helper protocol, but fetch credentials from the environment using the same logic as k8schain. Implementing this would mean we can use the standard docker credential file lookup logic, and change nothing about `ko` to support this. I'm not sure if it's easy to make this always "just work", especially when pulling public images -- do we fall back to anonymous appropriately?
2. Create an image containing:
    1. The go toolchain, probably just a `golang` base.
    2. `docker-credential-k8schain`.
    3. `ko`, on $PATH.
    4. `~/.docker/config.json`, wired up to use `docker-credential-k8schain`.
3. A pipeline on commit/release to create that image.
4. Some tests that verify this doesn't break. It is hard to test against different kube providers :/

An easier approach would be to just merge `gcr.io/kaniko-project/executor` and `golang`, then slap a `ko` binary on top.

**Comment by jonjohnsonjr** [comment]
This issue spawned https://medium.com/@jdolitsky/docker-credential-magic-a-magic-shim-for-docker-credential-helpers-deae9e78c2df

We should look at that as a solution.

**Comment by jonjohnsonjr** [comment]
https://github.com/google/ko/pull/528 👀

**Comment by imjasonh** [comment]
FYI the ko image doesn't have golang or creds installed at this time, and we shouldn't recommend it for general use just yet. But I'd like it to end up there, and for that to be a way to use it, with Tekton, GCB, etc.

**Comment by mattmoor** [comment]
Can I also plug for us to make sure that the appropriate credential helpers are installed for this to work in cluster contexts 🙏 

In `cosign` we added a `--k8s-keychain` flag to avoid the need for lots of heavy binaries, but if we're basing on `golang` already then YOLO

**Comment by imjasonh** [comment]
Sure, how do you want that to work?

I think a cred-less ko image is more useful than nothing, so if giving it creds blocks a release I'd say we can still punt and figure it out later.

**Comment by mattmoor** [comment]
So I'd say "Just `docker-credential-magician` the `golang` image" but that has problems because it'd invoke `docker-credential-gcr` for the distroless base in non-GCP contexts and fail to auth.

Honestly, the best answer I'm aware of is to use `k8schain` but nobody listens to me about that 🤣

**Comment by jonjohnsonjr** [comment]
> So I'd say "Just docker-credential-magician the golang image" but that has problems because it'd invoke docker-credential-gcr for the distroless base in non-GCP contexts and fail to auth.

I'd rather fix this than use k8schain

**Comment by mattmoor** [comment]
> I'd rather fix this than use k8schain

Yes, we've met 😉

**Comment by imjasonh** [comment]
I'd rather do anything besides expose a `--k8schain` flag to users, a cryptic string that holds no meaning to anyone but maybe four cursed individuals.

**Comment by mattmoor** [comment]
We didn't call it `k8schain` 🙃 

https://github.com/sigstore/cosign/blob/7e5ff000f6af25793631eb590964b9a861d672dc/cmd/cosign/cli/options/registry.go#L44-L45

**Comment by imjasonh** [comment]
> We didn't call it `k8schain` 🙃

ohthankgod 😅

**Comment by imjasonh** [comment]
This is done now. ghcr.io/google/ko
