### ISSUE TITLE
Ko naming / similar project

### ISSUE THREAD

**Issue by josephjacks** [google/ko#307]
Just noting this project with similar ambitions but is now somewhat dormant: https://github.com/kocircuit/kocircuit

CC @petar the creator

**Comment by jonjohnsonjr** [comment]
Interestingly these were hatched at similar times. I think they're different enough not to cause confusion (language vs image builder).

https://github.com/kocircuit/kocircuit/commit/3faeb8f46b5831a2dcda61fd52e6bd757f39f184

https://github.com/google/go-containerregistry/issues/80

**Comment by josephjacks** [comment]
> Interestingly these were hatched at similar times. I think they're different enough not to cause confusion (language vs image builder).
> 
> 
> 
> https://github.com/kocircuit/kocircuit/commit/3faeb8f46b5831a2dcda61fd52e6bd757f39f184
> 
> 
> 
> https://github.com/google/go-containerregistry/issues/80

Agree!

**Comment by jonjohnsonjr** [comment]
Perhaps the term was in the air due to https://en.wikipedia.org/wiki/AlphaGo 😉
