### ISSUE TITLE
ko resolve support for label filtering

### ISSUE THREAD

**Issue by mattmoor** [google/ko#31]
With `ko apply` I can supply a label filter to only deploy the pieces matching a particular label filter.

For example:
```
ko apply -f config -l "networking.knative.dev/ingress-provider!=istio"
```

Will install knative/serving without the Istio elements.  However, there are two problems with this:
1. This still builds filtered things (this is handled by `kubectl`).
2. This doesn't work with `ko resolve`.

I'd like to leverage the latter portion of this to enable us to release separate release bundles, e.g. `config/` would contain all of the "default" implementations, but we can still create split release bundles for core, istio, cert-manager separately using the label filter.

cc @n3wscott @jonjohnsonjr @ImJasonH

**Comment by mattmoor** [comment]
If we can land this in the next week or so, we can use this to release 0.6 👍

**Comment by jonjohnsonjr** [comment]
Fixed by https://github.com/google/ko/pull/46
