### ISSUE TITLE
Support setting Go build flags via configuration file

### ISSUE THREAD

**Issue by HeavyWombat** [google/ko#316]
Although, build flags [like `-ldflags` can be set using an environment variable](https://github.com/google/ko#how-can-i-set-ldflags), there is a problem if you want to set multiple linker flags like that. Since the [Go docs on the environment variables now state that spaces are not allowed](https://golang.org/cmd/go/#hdr-Environment_variables) in this context and specifying the flags multiple times does not work due to the way overrides are handled, I do not currently see a good way to specify multiple `ldflags`.  The use-case I have in mind would be to set `ldflags` for `-s`, `-w`, and `-X`, which is not an uncommon combination. In [GoReleaser this is solved by section in the configuration](https://goreleaser.com/customization/build/) to specify the respective settings, which I think is quite nice. Any chance that the `.ko.yaml` could be used for this kind of configuration, too? Thanks in advance for your feedback.

**Comment by jonjohnsonjr** [comment]
Yep, so someone has proposed something similar in the past: https://github.com/google/ko/issues/54#issuecomment-509900090

Ideally we could solve some problems with the `kodata` convention via the same mechanism: https://github.com/google/ko/issues/251

I am certainly open to it.

It would be _really_ interesting to see how much of the GoReleaser config could apply to us, because we could just use that exact struct for this... maybe even reuse the config file 🤔

**Comment by embano1** [comment]
Just wasted an hour hitting that issue too trying to inject multiple build time variables via `-X` linker flags. Would be great if this could be addressed in `ko`.

**Comment by jonjohnsonjr** [comment]
I would love to see this but don't have the bandwidth to do it myself at the moment.

In my mind, it seems somewhat straightforward to adapt the goreleaser config for our own purposes, but that may be more difficult than I'm imagining.

**Comment by jonjohnsonjr** [comment]
> Would be great to get some feedback as soon as I can share a branch with those ideas. Happy to PR it if you think it makes sense.

Happy to give feedback and would love to see how it looks. I think in the ideal case, you could literally take an existing goreleaser config file and just plop it down for `ko` to use, and it would "just work" (for the most part). I'm not 100% sure that goreleaser and ko have a 1:1 mapping, but I'm guessing we can get pretty close.

**Comment by HeavyWombat** [comment]
Like I said, I played around with the idea a bit. The code is [pushed to my fork](https://github.com/HeavyWombat/ko/tree/add/go-build-flag-overrides) now.

A `.ko.yaml` would look like this:
```yaml
defaultBaseImage: gcr.io/distroless/static:nonroot

build:
  flags:
  - -tags
  - netgo
  ldflags:
  - -s -w
  - -extldflags "-static"
```

Also, I use an environment variable to supply non-static flags to the build command:
```sh
export KO_GOBUILD_LDFLAGS="-X main.version=$(git describe --tags --always)"
```

The dummy Go app to test to play around:
```go
package main

import (
	"fmt"
	"runtime"
)

var version string

func main() {
	if len(version) == 0 {
		version = "undef"
	}

	fmt.Printf("foobar version %s (%s/%s, %s)\n",
		version,
		runtime.GOOS,
		runtime.GOARCH,
		runtime.Version(),
	)
}
```

Couple of things I thought about:
- GoReleaser supports multiple builds in its configuration, therefore it is a list in their configuration. Since `ko` places one binary into the container, I did not do the list in `.ko.yaml`.
- I see the use case for some fairly static flags that are quite commonly used, like build tags and ldFlags like `-s -w` to make the binary smaller. They make perfect sense in the `.ko.yaml` to me, because I want to set them and be done.
- There are also use cases where the build flags are context specific, for example version number. GoReleaser uses templates and the version number is on of the lucky fields to be available to be used in the configuration. This is not directly translatable to `ko` -- I think. This is why I played around with the idea of supplying additional build flags via `KO`-prefix environment variables (mimicking the existing `GOFLAGS` approach).

**Comment by embano1** [comment]
@HeavyWombat verified and works for me with multiple `LDFLAGS`, e.g.

```bash
export KO_GOBUILD_LDFLAGS="-X main.buildVersion=v0.1.0 -X main.buildCommit=123456AF -X main.buildTime=2021-04-06T11:53:52Z"
docker run --rm -it $(../ko-fork/ko publish -L .)
2021/04/06 13:57:53 Using base gcr.io/distroless/static:nonroot for github.com/embano1/dummy-ko-app
2021/04/06 13:57:53 No matching credentials were found for "gcr.io/distroless/static", falling back on anonymous
2021/04/06 13:57:54 Building github.com/embano1/dummy-ko-app for linux/amd64
2021/04/06 13:57:54 Loading ko.local/dummy-ko-app-bd999cafc91f62dcb340484e1a3d9501:01fa5e770c07d4d419b2ce4be4a6bfbbe727be13378e066bd796ea38bb899a16
2021/04/06 13:57:55 Loaded ko.local/dummy-ko-app-bd999cafc91f62dcb340484e1a3d9501:01fa5e770c07d4d419b2ce4be4a6bfbbe727be13378e066bd796ea38bb899a16
2021/04/06 13:57:55 Adding tag latest
2021/04/06 13:57:55 Added tag latest
version: v0.1.0
commit: 123456AF
date: 2021-04-06T11:53:52Z

```

**Comment by jonjohnsonjr** [comment]
> Since ko places one binary into the container, I did not do the list in .ko.yaml.

I think it can make sense to do a list, actually. A single `.ko.yaml` file can contain base image overrides for multiple import paths, and many projects contain multiple binaries. See [here](https://github.com/google/ko#overriding-base-images) for how you can override the base image for multiple import paths under `baseImageOverrides`.


I'd like to be able to use the same file to configure these different binaries, even if they end up in separate container images. We might be able to use goreleaser's `dir` field to distinguish which build object is for which image? Or add our own field to distinguish

**Comment by HeavyWombat** [comment]
> > Since ko places one binary into the container, I did not do the list in .ko.yaml.
> 
> I think it can make sense to do a list, actually. A single `.ko.yaml` file can contain base image overrides for multiple import paths, and many projects contain multiple binaries. See [here](https://github.com/google/ko#overriding-base-images) for how you can override the base image for multiple import paths under `baseImageOverrides`.
> 
> I'd like to be able to use the same file to configure these different binaries, even if they end up in separate container images. We might be able to use goreleaser's `dir` field to distinguish which build object is for which image? Or add our own field to distinguish

Good point! Missed that completely. I will change that. So either `main` or `dir` or both could be used to identify the entry in the list by comparing it to the given `ko` import path. Have to have a look whether this idea works.

**Comment by HeavyWombat** [comment]
@jonjohnsonjr @embano1 I rewrote my last idea to address the feedback. The `.ko.yaml` would now have a section that is actually identical to GoReleaser. The respective entry is picked by matching the import path against the `dir` and `main` fields. I even tried to put my thoughts into the README already to make sure it is somewhat possible to explain the idea in a few sentences. Using the actual GoReleaser `build` struct was nice in terms of parsing. Let me know whether you think this is an appropriate setup. So far, _only_ the fields `flags` and `ldflags` are supported, but we could add support for other fields like the `asmflags` or even their templating later. Code is [pushed to my fork](https://github.com/HeavyWombat/ko/tree/add/go-build-flag-overrides).

**Comment by HeavyWombat** [comment]
Actually, happy to make it a PR now. Could make sense now.

**Comment by embano1** [comment]
Since I use goreleaser and ko together a lot, I'm fine from an UX perspective to follow the goreleaser configuration format. Do you think it would be good to also have a section for additional container builds, e.g. if someone needs helper containers to be built (e.g. from vendor)? In knative we use this approach currently: https://github.com/vmware-tanzu/sources-for-knative/blob/main/test/upload-test-images.sh

From my PoV it would be nice to collapse this into the config too. Just my 2ct and not sure if it's too big for your current PR scope. But might be worth mentioning/following up.
