### ISSUE TITLE
Remove k8s deps if possible

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#317]
I added these [forever ago](https://github.com/google/go-containerregistry/pull/297) to get kubectl flags, but it's been a source of endless trouble...

See https://github.com/google/ko/issues/315#issuecomment-783718564 for a recent issue.

**Comment by dprotaso** [comment]
might be able to use https://github.com/kubernetes-sigs/controller-runtime

**Comment by jonjohnsonjr** [comment]
Can you elaborate a bit?

**Comment by dprotaso** [comment]
sigh - sorry wrong repo - I meant to link - https://github.com/kubernetes/cli-runtime - that pulls out some common runtime logic - ie. flags & reading yaml files

but I realize it depends on k8s upstream libs as well and unfortunately with `replace` directives :(

**Comment by dprotaso** [comment]
the replace directives match the versions in the `require` block so maybe it's just automation playing safe
