### ISSUE TITLE
Cannot install ko

### ISSUE THREAD

**Issue by vishvananda** [google/ko#32]
command fails to find a dependency:

```
$ go get github.com/google/ko/cmd/ko
go: finding github.com/google/ko/cmd/ko latest
go: finding github.com/google/ko/cmd latest
go: finding github.com/google/ko latest
go: finding k8s.io/kubernetes/pkg/kubectl/genericclioptions latest
go: finding k8s.io/kubernetes/pkg/kubectl latest
go: finding k8s.io/kubernetes/pkg latest
build github.com/google/ko/cmd/ko: cannot load k8s.io/kubernetes/pkg/kubectl/genericclioptions: cannot find module providing package k8s.io/kubernetes/pkg/kubectl/genericclioptions
```

It looks like the package moved to `k8s.io/kubernetes/pkg/runtime-cli/genericclioptions`

**Comment by vishvananda** [comment]
well somehow it was not using the vendor dir. For some reason running the install from inside gopath fixed whatever was broken and now it works corretly.

**Comment by taragu** [comment]
@vishvananda I'm running into the same issue. It wasn't resolved regardless of which directory I ran `go get github.com/google/ko/cmd/ko`. It still chocked on
```
build github.com/google/ko/cmd/ko: cannot load k8s.io/kubernetes/pkg/kubectl/genericclioptions: cannot find module providing package k8s.io/kubernetes/pkg/kubectl/genericclioptions
```

**Comment by taragu** [comment]
This worked: https://github.com/google/ko/issues/37#issuecomment-501688095
