### ISSUE TITLE
ko:// references to missing import paths are ignored

### ISSUE THREAD

**Issue by pianohacker** [google/ko#328]
When applying manifests containing `ko://` references to import paths that don't exist locally, `ko apply` and `ko resolve` will ignore those references and pass them on to Kubernetes unchanged.

I think this is fairly confusing. It seems to date from back before explicit `ko://` references existed. If I'm explicitly stating in my YAML that the image should be built with `ko://`, I would prefer to be told I forgot to `go get` the code in question than be told that I have an invalid image reference by Kubernetes.

**Comment by jonjohnsonjr** [comment]
What version of `ko` are you using? This should be fixed?

**Comment by pianohacker** [comment]
This absolutely was, in 0.8.0. Found this out while talking to maintainers on Slack, didn't close this issue. Sorry for the fuss.
