### ISSUE TITLE
gotcha when $GOPATH/src includes directories with simple names matching yaml values

### ISSUE THREAD

**Issue by jldec** [google/ko#34]
Directory names like `$GOPATH/src/hello/`... which happen to match a value inside the yaml passed to ko, will confuse the go package import path replacement logic.

e.g. if the resource yaml contains
```yaml
metadata:
  name: hello
```
ko will match `hello` as being a reference to a go package, and will try to build that package and replace the key with something like
```yaml
metadata:
  name: ko.local/hello:a2071d056f02353fc6bdf16c3cb9739437e648a5df8e7a821117c1e020245e15
```
This will result in errors when applying the yaml to k8s.

**Comment by ImJasonH** [comment]
I think we should close this as a subset of the problem described in https://github.com/google/ko/issues/9
