### ISSUE TITLE
Feature Request: custom base image from local docker daemon

### ISSUE THREAD

**Issue by misterikkit** [google/ko#368]
It would be convenient to specify a `customBaseImage` from my local docker daemon. If I tag an image as `foo:1` then ko will search index.docker.io. If I tag as `ko.local/foo:1` then ko will try to dial `ko.local`.

I have a project in which several containers are built from a common base image, and the base image is also built in the same project. The current build flow is something like,
```sh
$ docker build -t base:0.1 -f base/Dockerfile .
$ docker build -t foo:0.1 -f foo/Dockerfile .
$ cat foo/Dockerfile
FROM base:0.1
...
```

**Comment by jonjohnsonjr** [comment]
https://github.com/google/ko/pull/371 just assumes `ko.local` things are in the daemon, not any other domain (or images without a domain), would that work for you?

**Comment by misterikkit** [comment]
@jonjohnsonjr Yeah I think that would solve the use case I was hitting. At this point, I am just experimenting with ko. Integrating it into my CI/build pipelines would involve propagating that `ko.local` prefix to many places.
