### ISSUE TITLE
Change to bullseye?

### ISSUE THREAD

**Issue by dlorenc** [google/ko#418]
We now have distroless builds for buster out! We have this set so far:

```shell
static-debian11:latest-amd64
static-debian11:nonroot-amd64
static-debian11:debug-amd64
static-debian11:debug-nonroot-amd64
static-debian11:latest-arm64
static-debian11:nonroot-arm64
static-debian11:debug-arm64
static-debian11:debug-nonroot-arm64
static-debian11:latest-arm
static-debian11:nonroot-arm
static-debian11:debug-arm
static-debian11:debug-nonroot-arm
static-debian11:latest-s390x
static-debian11:nonroot-s390x
static-debian11:debug-s390x
static-debian11:debug-nonroot-s390x
static-debian11:latest-ppc64le
static-debian11:nonroot-ppc64le
static-debian11:debug-ppc64le
static-debian11:debug-nonroot-ppc64le
base-debian11:latest-amd64
base-debian11:nonroot-amd64
base-debian11:debug-amd64
base-debian11:debug-nonroot-amd64
base-debian11:latest-arm64
base-debian11:nonroot-arm64
base-debian11:debug-arm64
base-debian11:debug-nonroot-arm64
base-debian11:latest-arm
base-debian11:nonroot-arm
base-debian11:debug-arm
base-debian11:debug-nonroot-arm
base-debian11:latest-s390x
base-debian11:nonroot-s390x
base-debian11:debug-s390x
base-debian11:debug-nonroot-s390x
base-debian11:latest-ppc64le
base-debian11:nonroot-ppc64le
base-debian11:debug-ppc64le
base-debian11:debug-nonroot-ppc64le
```

I think that's enough for `ko`, should we start testing and switch the default?

**Comment by jonjohnsonjr** [comment]
Why on earth would you name them like this?

**Comment by dlorenc** [comment]
Which part? None of this is new really. There were 10s everywhere that there are now 11s. I think a bunch of these are also multi-platform images.

**Comment by jonjohnsonjr** [comment]
None of the ones in that list are multi-platform. I'd drop all the platform-specific tags and just have multi-platform images only.

Encoding nonroot+debug in the tag is dumb, can those be in the repository path instead?

**Comment by dlorenc** [comment]
> Encoding nonroot+debug in the tag is dumb, can those be in the repository path instead?

PRs welcome!

> None of the ones in that list are multi-platform. I'd drop all the platform-specific tags and just have multi-platform images only.

It doesn't work that way. Looks like we need to update this script to add the multi-arch 11's too: https://github.com/GoogleContainerTools/distroless/blob/main/cloudbuild_docker.sh#L28

**Comment by imjasonh** [comment]
Naming aside, this begs the question of how we should roll out changes to the base image `ko` uses by default. In #160 we switched from rootful to `:nonroot` distroless, with a warning and a release before switching the default. Should we do that again for buster (and presumably 12, 13, etc., as they come out)? That seems pretty choresome, especially when we expect users not to care in most cases.

Can distroless just change its definition of `gcr.io/distroless/static:nonroot` to point to buster, then 12, 13, etc.? If users want to pin to a specific Debian version they can do so with `-debian11` etc., and `ko` just wouldn't by default.

**Comment by dlorenc** [comment]
Ref https://github.com/GoogleContainerTools/distroless/issues/876

It looks like ko still uses debian10. From some logs today on ko 0.9.3:

```
2021/10/25 00:04:44 Using base gcr.io/distroless/base-debian10 for github.com/sigstore/fulcio
```

**Comment by benmoss** [comment]
It looks like distroless/static:nonroot is already bullseye:

```
→ crane export gcr.io/distroless/static:nonroot - | tar -xO ./usr/lib/os-release
PRETTY_NAME="Distroless"
NAME="Debian GNU/Linux"
ID="debian"
VERSION_ID="11"
VERSION="Debian GNU/Linux 11 (bullseye)"
HOME_URL="https://github.com/GoogleContainerTools/distroless"
SUPPORT_URL="https://github.com/GoogleContainerTools/distroless/blob/master/README.md"
BUG_REPORT_URL="https://github.com/GoogleContainerTools/distroless/issues/new"
```

**Comment by imjasonh** [comment]
Indeed, a `ko`-built image (built a while ago) is based on bullseye:

```
$ crane export gcr.io/tekton-nightly/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:7917ba5196b1a43058452ff93cd47e7255a73d4a45e56c7810d3f03e2e15e693 - | tar -xO ./usr/lib/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
