### ISSUE TITLE
RFC: `ko build` as a preferred alias for `ko publish`

### ISSUE THREAD

**Issue by imjasonh** [google/ko#451]
I don't remember at what point we decided to call the command to just build and push images `publish` -- I assume it was back in the days the repo was part of ggcr, and probably was based on the fact that the package/interface that did it was called `publish`.

Either way, this isn't a great way to decide what to call this command, and I think we would benefit from changing it to `ko build`. This mirrors `go build`, `docker build`, and `pack build`, among many others. AFAIK nothing else anywhere uses the term `publish` for this. "Publish" is even a bit of a misnomer if you're using `ko.local` to "publish" to local daemon storage.

`ko build` would be a permanent alias for `ko publish`, and we'd only update documentation to prefer `ko build` -- we shouldn't warn or emit spammy logs if folks are still using `ko publish`, and we wouldn't remove the sub-command at any time in the future.

What do you think?

@jonjohnsonjr @mattmoor

**Comment by imjasonh** [comment]
Cobra makes this very easy: https://github.com/google/ko/compare/main...imjasonh:ko-build

**Comment by mattmoor** [comment]
Generally I'm +1, but this is commonplace enough that I think we should have a looooong deprecation period for `publish`, or ~always support it, but hide it or something.

**Comment by imjasonh** [comment]
Yeah, I'm fine with just keeping it around as an alias forever, especially since cobra makes it so easy.

**Comment by jonjohnsonjr** [comment]
SGTM
