### ISSUE TITLE
Applications built by Ko complains about GitHub commit id missing from kodata

### ISSUE THREAD

**Issue by afrittoli** [google/ko#48]
Applications built by ko generate a lot of lines like this in CI logs (I'm looking at Tekton CI for instance https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_pipeline/995/pull-tekton-pipeline-integration-tests/1144026938617106434/build-log.txt):

```
I0626 23:56:51.574] [gopath-test] [step-test-build] {"level":"warn","ts":1561593313.3031838,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
```

As far as I understand, setting the commit ID in kodata is not mandatory, so this should not be logged at "warn" level, which generates a lot of noise when troubleshooting actual issues.

I would propose reducing the log level to info at least, or even better to debug so that it could be filtered out during normal operations.

**Comment by jonjohnsonjr** [comment]
That's coming from [here](https://github.com/knative/pkg/blob/222dd25986d91c12d54f6ac7758251f005053b8f/logging/config.go#L69), not `ko`.

**Comment by afrittoli** [comment]
oh, thanks!

**Comment by JCzz** [comment]
@afrittoli How did you solve this?

**Comment by jonjohnsonjr** [comment]
@JCzz that error means you're using knative.dev/pkg/logging, which could fail in a couple ways:

1. You're not symlinking to HEAD, e.g. see here: https://github.com/knative/serving/tree/4f7130bc97dfdf0040dd0975e27451a5097abfad/cmd/controller/kodata
2. You're using an old version of `ko` that doesn't chase symilnks, see here: https://github.com/google/ko/pull/73
