### ISSUE TITLE
ko with monorepo

### ISSUE THREAD

**Issue by xmlking** [google/ko#51]
I have a monorepo (using go modules) https://github.com/xmlking/micro-starter-kit
Where multiple deployable  services sharing common code.
Will ko support monorepos? What is the best practice to layout and use ko with monorepos

**Comment by jonjohnsonjr** [comment]
See my comment here https://github.com/google/ko/pull/50#issuecomment-509421373

I believe we would just look for the root `go.mod` file and use that to locate packages. With a monorepo, do you have multiple `go.mod` files?

**Comment by xmlking** [comment]
i only have one `go.mod`  at monorepo root. but multiple containerise-able  services in `/srv` sharing common code in `/shared`

Tested and it is working fine with [image: github.com/xmlking/micro-starter-kit/srv/account](https://github.com/xmlking/micro-starter-kit/blob/master/deploy/300-deployment.yaml#L24) in `deployment.yaml`

**Comment by jonjohnsonjr** [comment]
We landed go module support a while ago. Is this still an issue for you @xmlking ?

**Comment by xmlking** [comment]
no , thanks
