### ISSUE TITLE
Vulnerability warning

### ISSUE THREAD

**Issue by naveensrinivasan** [google/ko#517]
Scorecard uses https://github.com/ossf/scorecard/blob/f9b9773e2f4632b48b21765413f069504be40714/tools/go.mod#L9 `ko`. 

We have vulnerability warning and that is due to this https://deps.dev/go/github.com%2Fgoogle%2Fko/v0.9.3 specifically `github.com/opencontainers/image-spec`. Would `ko` be able to address this vulnerability?

We understand it is a `low`. But it would be helpful if it can be fixed. 
Thanks

**Comment by imjasonh** [comment]
The fix is in at heard if you want to avoid the alert.

In addition to being a low priority issue, the vulnerability doesn't affect ko or go-containerregistry in any way, so it can be safely ignored/dismissed.

**Comment by naveensrinivasan** [comment]
Thanks, I am going to pull the head.
