### ISSUE TITLE
[Docs] Possible outdated documentation

### ISSUE THREAD

**Issue by wesleytanws** [google/ko#523]
We have identified **`1`** possible instance of outdated documentation:

- [ ] [`Last-Modified`](https://github.com/google/ko/blob/18096666c949ff2e00bbff4c6589ea82c5c70376/vendor/github.com/emicklei/go-restful/constants.go#L16) was deleted but the change has not been reflected in the current version of the [README](https://github.com/google/ko/blob/6ff346909c2cf642d0b6152e2f3b8867c10fe4da/README.md) file

#### About
This is part of a research project that aims to automatically detect outdated documentation in GitHub repositories. We are evaluating the validity of our approach by identifying instances of outdated documentation in real-world projects.

We hope that this research will be a step towards keeping documentation up-to-date. If this has been helpful, consider updating the documentation to keep it in sync with the source code. If this has not been helpful, consider updating this issue with an explanation, so that we can improve our approach. Thanks!

**Comment by imjasonh** [comment]
This is a spammy false positive.

**Comment by imjasonh** [comment]
To avoid spamming real maintainers, I'd suggest forking these repos and filing issues on your fork, until the false positive rate is much lower.
