### ISSUE TITLE
.Env doesn't seem to allow custom environment variables

### ISSUE THREAD

**Issue by StevenACoffman** [google/ko#552]
Hi 👋 ! 
When I tried to use my own environment variable (`APP`) as in the README example, I found it gave me an error:
```
2021/12/16 19:48:53 Using base gcr.io/distroless/static:nonroot for github.com/StevenACoffman/repro/sub
2021/12/16 19:48:55 Using build config my-build for github.com/StevenACoffman/repro/sub
Error: failed to publish images: error building "ko://github.com/StevenACoffman/repro/sub": template: argsTmpl:1:60: executing "argsTmpl" at <.Env.APP>: map has no entry for key "APP"
2021/12/16 19:48:55 error during command execution:failed to publish images: error building "ko://github.com/StevenACoffman/repro/sub": template: argsTmpl:1:60: executing "argsTmpl" at <.Env.APP>: map has no entry for key "APP"
```
I'm using MacOS X amd64 and Go 1.17.5 (installed with ASDF, 😉) and I updated my [StevenACoffman/repro](https://github.com/StevenACoffman/repro) repository to reproduce it

When I execute this after having cloned that repository:
```
cd sub
./ko.sh
```
I can reliably reproduce that error.

**Comment by imjasonh** [comment]
I'm able to reproduce given your repo (_thank you for providing that_ 🙏 ).

The issue goes away for me if you `export APP` (and others). Maybe we just need to document that these need to be `export`ed?

**Comment by halvards** [comment]
This is about shell handling of envvars, and not specific to `ko`.

As @imjasonh suggests, you can `export` them, which makes them available to the child process (`ko` in this case).

Alternatively, you can provide them in the command when you execute `ko` (without exporting):

```
APP=foo ko publish ...
```

This is a good explanation from StackExchange: https://unix.stackexchange.com/a/130989

**Comment by StevenACoffman** [comment]
🤦 Oh duh... I can't believe I forgot to export the variables. Thanks, and sorry to waste your time!
