### ISSUE TITLE
Introduce log levels

### ISSUE THREAD

**Issue by halvards** [google/ko#560]
When using `ko` as a library, it can be helpful to have more control of the log output.

If a downstream tool enables debug or trace level logging, it could then propagate this setting to `ko`. Likewise, a downstream warning log level could translate to having `ko` only output warnings (e.g., with #542).

For instance, while developing features for #348 and https://github.com/GoogleContainerTools/skaffold/issues/6041, I often added debug log lines to `ko` that I removed before committing changes.

One approach would be to follow the approach in `ggcr`: https://github.com/google/go-containerregistry/blob/v0.7.0/pkg/logs/logs.go#L24-L31

This would also allow downstream tools to plug in their logging libraries by sending `ko` log output to another destination using [`log/Logger.SetOutput`](https://pkg.go.dev/log#Logger.SetOutput), like what `ko` does with `ggcr`: https://github.com/google/ko/blob/v0.9.3/cmd/ko/main.go#L39-L40

And just to be clear, I'm not suggesting introducing a logging library!

**Comment by jonjohnsonjr** [comment]
I have some regrets about the global logging stuff in ggcr. I would be fine with adopting https://github.com/go-logr/logr if we want to expose this.

**Comment by halvards** [comment]
What regrets do you have with the `ggcr` approach? I like the simplicity of it, which unsurprisingly aligns with `ko` :smile:.

On https://github.com/go-logr/logr, libraries/SDKs should log to interfaces IMHO, so that aligns with my principles, but that'll be a bigger change. Is the goal to inject logger instances rather than reaching for global variables? Or do you see benefits in the structured logging or numbered levels?

**Comment by jonjohnsonjr** [comment]
> What regrets do you have with the ggcr approach? I like the simplicity of it, which unsurprisingly aligns with ko 😄.

The fact that's it's package-level globals is kinda gross. I'm not sure if adding a logger option is much better, but I do hate globals :)

> but that'll be a bigger change

Agreed... I'm assuming you'd want to expose this for use by skaffold? Otherwise we could keep it internal.

>  Is the goal to inject logger instances rather than reaching for global variables?

Yup!
