### ISSUE TITLE
support generating an SBOM file based on CycloneDX format in addition to go.version-m and spdx

### ISSUE THREAD

**Issue by developer-guy** [google/ko#563]
According to the comment https://github.com/sigstore/cosign/issues/959#issuecomment-987306342, we can use [cyclonedx-go](https://github.com/CycloneDX/cyclonedx-go) library to generate an SBOM file based on CycloneDX format, so, we can accept `cyclonedx` as an alternative in --sbom flag.

WDYT @mattmoor @imjasonh?

**Comment by developer-guy** [comment]
please feel free to assign it to me that I'm willing to work on it.

**Comment by mattmoor** [comment]
I think @imjasonh and I would both be on board with that.  Hopefully it's dependencies aren't crazy 🤞

**Comment by imjasonh** [comment]
Sounds great! Feel free to start hacking, and let us know if you hit any issues. I'm also curious if the dependency will turn out to be heavy, but we can assess that when there's something more concrete to discuss.

Thanks for taking this up!
