### ISSUE TITLE
Using ko with a private registry

### ISSUE THREAD

**Issue by deissnerk** [google/ko#57]
I'm using ko with a private image registry and need to configure the use of a certain imagePullSecret into the yaml that is sent to the cluster. So far I use kustomize for this, but this means that I have to create a kustomization.yaml in the original project and list all yaml file in there.  I also have to make sure that I add the imagePullSecret to all service accounts or deployments. Over all this is very error prone.
I wonder, if ko could take as a parameter the path of a yaml containing the image pull secret. It could then add an imagePullSecrets section to all yamls where it replaces go package names with docker images.

**Comment by jonjohnsonjr** [comment]
Interested in what others think, but I'm weakly opposed to adding something like this. One of the nice (and [awful](https://github.com/google/ko/issues/9)) things `ko` is that it's oblivious to kubernetes resource structures, which makes the tool incredibly simple (and stupid).

Kustomize seems like the right tool for doing something like this, but I haven't used it that much.

I'd lean towards writing a separate tool that adds `imagePullSecrets` to any resource you can [duck](https://godoc.org/github.com/knative/pkg/apis/duck) type to a [`PodSpecable`](https://github.com/knative/pkg/blob/07104dad53e803457a95306e5b1322024bd69af3/apis/duck/podspec_test.go#L32) if the `image` starts with `$KO_DOCKER_REPO`, e.g.:

```
$ ko resolve -f config/ | add-secrets --repo $KO_DOCKER_REPO --secrets ~/foo.yaml | kubectl apply -f -
```

Then you can decouple this entirely from `ko`, but coordinate with it via the `--repo` flag.

That being said, if we did want to add this to `ko` via a flag, you'd need to plumb that option down to [`resolve.ImageReferences`](https://github.com/google/ko/blob/0df8b2497e7eb7dc6308cffe926d0976b7cc8532/pkg/resolve/resolve.go#L31), and conditionally try to detect `PodSpecable` things [here](https://github.com/google/ko/blob/0df8b2497e7eb7dc6308cffe926d0976b7cc8532/pkg/resolve/resolve.go#L124-L137), then if `builder.IsSupportedReference` is true for for anything in `Spec.Containers` or `Spec.InitContainers`, append your secrets to `Spec.ImagePullsecrets`.

**Comment by deissnerk** [comment]
Sorry, for following up so late, but I somehow lost track of a few things over the summer vacation. 😃 
Thanks @jonjohnsonjr, I like the idea of a separate tool. Feel free to close this issue, if you decide not to implement this functionality in ko.

**Comment by jonjohnsonjr** [comment]
> I somehow lost track of a few things

Story of my life.

> I like the idea of a separate too

If you end up implementing something like this, definitely ping back here. I'd probably be interested in using it, and it might make sense to link to it from here. Going to close this for now, though.

Cheers.
