### ISSUE TITLE
Cut a v0.10 release

### ISSUE THREAD

**Issue by jdolitsky** [google/ko#584]
Currently using `--image-refs` flag, and causing issues for developers instructed to install `ko`.

Is there are holdup on cutting a release with this feature?

**Comment by imjasonh** [comment]
+1 from me. I think we had hoped to get more SBOM options and maybe signing in before the next release, but this is already so jam-packed I think we can just bump those to v0.11.

@jonjohnsonjr any concerns?

**Comment by imjasonh** [comment]
Looking at open PRs:

- https://github.com/google/ko/pull/471 - needs rebase @tcnghia 
- https://github.com/google/ko/pull/581 - I'd like to get in

Other than that, I think we're good to go?

**Comment by mattmoor** [comment]
+1 from me 🤩 

The lack of release here came up with me encouraging Karpenter to use `--image-refs` and get free SBOMs.

**Comment by jdolitsky** [comment]
RELEASE THE KRAKEN

**Comment by imjasonh** [comment]
I'd like to! I think the only thing we're really waiting on is #586 which depends on https://github.com/awslabs/amazon-ecr-credential-helper/pull/309

**Comment by mattmoor** [comment]
I think we are waiting on an ECR patch worth linking here
