### ISSUE TITLE
Support loading images into K3s

### ISSUE THREAD

**Issue by imjasonh** [google/ko#588]
Similar to how we load images into KinD with `KO_DOCKER_REPO=kind.local`, we should support loading images into Rancher Desktop / k3s, which uses containerd.

https://cwienczek.com/2020/06/import-images-to-k3s-without-docker-registry/ indicates that you can run:

```
sudo k3s ctr images import /home/ubuntu/test-app-v1.0.0.tar
```

The Slack user `Romāns Potašovs` who originally asked about this feature says you can also:

```
docker save my_app:latest | ctr -a /run/k3s/containerd/containerd.sock -n=k8s.io images import -
```

In which case, this should be fairly straightforward, either by piping that output into an `exec.Command`, or by figuring out what library we'd need to import to accomplish the same thing. Shelling out might be better for our dependency graph (same for KinD, honestly).

This needs more investigation. If you have experience with k3s, and are interested in helping here, let me know.

**Comment by kameshsampath** [comment]
@imjasonh - https://github.com/google/ko/pull/665 has raw implementation for it, seem to work  for both rancher-desktop and vanilla lima-vm. 

Got some TODOs added to it, happy to work on them when you feel if the approach looks OK.

Sadly there are no mocks for lima-vm( may be I dont know ;)) so test cases are kind of missing.
