### ISSUE TITLE
ux: consider do not enforce `KO_DOCKER_REPO` variable if `--push=false`

### ISSUE THREAD

**Issue by Dentrax** [google/ko#590]
Since we can pass `--push=false`, in this case `$KO_DOCKER_REPO` env flag could be useless to check whether it's set or not. It should be only checked if we're pushing image to remote. Wdyt?

```
$ ko publish --bare -B --platform=linux/amd64 --tags latest --push=false --oci-layout-path oci-dir .
Error: error creating publisher: KO_DOCKER_REPO environment variable is unset
2022/02/10 10:01:55 error during command execution:error creating publisher: KO_DOCKER_REPO environment variable is unset
```

**Comment by dirien** [comment]
Created a PR for this https://github.com/google/ko/pull/604, was good to get used with the codebase.
