### ISSUE TITLE
ko blocked waiting for google credential helper

### ISSUE THREAD

**Issue by n3wscott** [google/ko#598]
I consistently get halting when trying to ask ko to create several images in one bash script. All the usage of ko is using the publish command, never gets stuck on the same image. Sometimes it will do 2-3, sometimes it will finish 5-6 but it gets stuck about 90% of the time. I have to `kill -9` the ko process, and I get this output from ko:

```
error resolving image references: error getting credentials - err: signal: killed, out: ``
```

It will stay stuck presumably blocked on the cred helper indefinitely. 

I have tried using both gcloud and gcr (env mode that does not use gcloud) in the docker config and they both seem to block. 

I am sending my images to `gcr.io`. I have a M1Max Mac.

**Comment by n3wscott** [comment]
oh, using ko at head. `v0.9.4-0.20220213235838-0187841b1641`

**Comment by imjasonh** [comment]
Also: what version of gcloud and/or docker-credential-gcr? Updating both of those might make this disappear.

**Comment by n3wscott** [comment]
```
(╯°□°)╯︵  gcloud --version
Google Cloud SDK 363.0.0
alpha 2021.10.29
bq 2.0.71
core 2021.10.29
gsutil 5.4
```

```
¯\(°_o)/¯ docker-credential-gcr version
Google Container Registry Docker credential helper 2.0.4
```

**Comment by imjasonh** [comment]
> ok removing the cred helpers still caused a block.
> 
> ```
> error resolving image references: error getting credentials - err: signal: killed, out: ``
> ```

That error seems to be coming from https://github.com/docker/docker-credential-helpers/blob/master/client/client.go#L45 which indicates it's invoking an external cred helper binary with the `store` arg -- do you have any `credsStore` configured?

**Comment by n3wscott** [comment]
OK! update, I had a `~/docker/.config.js` which is `{}` but `~/docker/.config.js` still had the cred helpers... Trying again.

**Comment by n3wscott** [comment]
LOOKING REALLY GOOD!! Removing the cred helpers with the latest ko version seems to be the ticket!!

THANKS SO MUCH @imjasonh, I owe you a beverage of your choice next time I see you.
