### ISSUE TITLE
supporting text/spdx+json format for SPDX 

### ISSUE THREAD

**Issue by developer-guy** [google/ko#602]
ko creates an SBOM file based on mediaType `text/spdx` by default, which is great, but according to the cosign's SBOM spec, there are other [mediaTypes](https://github.com/sigstore/cosign/blob/main/specs/SBOM_SPEC.md#mediatypes) that we can use, one of them is `text/spdx+json`, so, if we can support that, we can pipe the SBOM result to the great project [Grype](https://github.com/anchore/grype) (thanks to @luhring and his team) to scan packages against vulnerabilities.

```shell
$ KO_DOCKER_REPO=index.docker.io/devopps ko build -B ./
$ crane blob index.docker.io/devopp@<sha_of_the_sbom_layer> | grype sbom:-
```

WDYT @mattmoor @imjasonh @dentrax @dlorenc?

**Comment by imjasonh** [comment]
Sure!

Questions for you:
- Does grype only support SPDX+JSON?
- Do you have an example SBOM we could use to help us with the structure of the output?
- Does the spdx validator support the JSON format?

Questions for me:
- We probably do want to produce SPDX and CycloneDX both by default, but we probably don't want to produce all the format variations of both. Should the flag be `--sbom=cyclonedx,spdx-json` or something?
- What should the default formats be?
- Should `ko deps` fetch pre-generated SBOMs if it can find them, so you can just `ko deps <img> | grype`? And, should it generate and push SBOMs if they don't already exist?🤔

**Comment by imjasonh** [comment]
Instead of _additionally_ supporting SPDX+JSON, #660 is about _only_ generating the JSON of SPDX, instead of its text form.

I think #660 supersedes.
