### ISSUE TITLE
feature: Add a flag to set the directory to build/apply from

### ISSUE THREAD

**Issue by tstromberg** [google/ko#617]
I'd like to run many `ko apply` commands in parallel, but have run into an issue: ko only applies to the current working directory, and there can be only one current working directory within a process. 

This means that a parent process has to fork, change working directory, and fork again to execute ko. This is easy in some languages, but not so easy if you are using bash or xargs to coordinate the work.

Since 4.3BSD, tar has included a similar flag that I would probably mimic:

```
  -C, --directory=DIR        change to directory DIR
```

If this sounds good, please let me know and I'll throw a PR your way.

**Comment by imjasonh** [comment]
+1!

See also https://github.com/golang/go/issues/50332

**Comment by tstromberg** [comment]
Excellent news! I've created https://github.com/google/ko/pull/619 - PTAL :)

**Comment by jonjohnsonjr** [comment]
@tstromberg still want this?
