### ISSUE TITLE
Not working: Apple Silicon Mac

### ISSUE THREAD

**Issue by 54m** [google/ko#620]
x86_64 ✅
![image](https://user-images.githubusercontent.com/30588003/155869098-3e5d49d7-997d-4266-94cf-7de06b676f8a.png)

arm64 ❌
![image](https://user-images.githubusercontent.com/30588003/155869113-483bf162-a01e-4c94-8386-f9946bf2f1be.png)

**Comment by imjasonh** [comment]
In the second example, it sounds like Docker isn't running. Is that the case?

Are you able to publish to a registry?

**Comment by 54m** [comment]
@imjasonh 
Sorry, I restarted my Mac this morning and it was fixed.
Thank you for your comment. Close this issue
