### ISSUE TITLE
define a container image specific section in ko's configuration file

### ISSUE THREAD

**Issue by developer-guy** [google/ko#626]
We (w/@dentrax) thought that there is a specific section for Go binaries in order to define options while building them including ldflags, flags, envs, etc. So, it'd be nice if we can do the same for container images while building them. The first options that came to my mind are specifying annotations, labels, etc. 

```shell
images:
- id: <image>
  annotations:
  - foo=bar
  labels:
  - foo=baz
```

**Comment by imjasonh** [comment]
Could we add these to the existing `builds:` section?

I also wonder if we want to have some default section, since I suspect most of these labels/annotations are going to be the same across all images in a repo (version, repo, author, etc.)

**Comment by developer-guy** [comment]
can you please assign it to me 🤩

**Comment by developer-guy** [comment]
kindly ping @imjasonh, it is not completed, waiting for PR to be merged 🫣

**Comment by imjasonh** [comment]
Sorry for the delay. Is this an urgent need? I haven't personally found much need to set arbitrary labels and annotations on ko-built images, but if that's something you need I'd love to know more about your use case.
