### ISSUE TITLE
Sharp increase in resource usage between v0.9 and v0.10

### ISSUE THREAD

**Issue by antoineco** [google/ko#642]
In a project with [about 60 `ko://` references](https://github.com/triggermesh/triggermesh/blob/main/config/500-controller.yaml#L59), we are seeing a sudden increase in the resource usage in our CI workers, causing all our release jobs to fail due to `go build` processed being killed.

Judging by the logs (`"Building github.com/triggermesh/triggermesh/cmd/..."`), it seems like builds are now started all at once, without respecting `nprocs`. This wasn't the in v0.9 (again, only judging by the logs).

Before

![image](https://user-images.githubusercontent.com/3299086/157438381-4caf3fc2-c20b-4600-80b1-5f73c2a43ec6.png)

After

![image](https://user-images.githubusercontent.com/3299086/157438297-b1477c54-ede5-448a-9ca1-ebf4c1e4b284.png)

**Comment by antoineco** [comment]
@imjasonh No, no building of multi-platform images.
I'll try disabling SBOM generation and report back.

**Comment by mattmoor** [comment]
No, but I'll ask around 🤔

**Comment by antoineco** [comment]
Same issue with `--sbom=none`. The CPU is maxed out and `go build` processes are being killed by the OOM killer.

**Comment by dprotaso** [comment]
@antoineco how do you get graphs like that?


I'm curious if we need something like 
https://github.com/uber-go/automaxprocs

**Comment by antoineco** [comment]
@dprotaso They are from CircleCI.

I didn't have time to investigate further yet, but I have a feeling parallelism isn't regulated at all anymore. Based solely on the logs output, we used to observe `nprocs` builds concurrently. Now all builds seem to start at once. And since we have ~60 images to build during releases, it OOMs almost instantly.

**Comment by dprotaso** [comment]
Playing with Circle CI - by default it reads GOMAXPROCS as 36, but using automaxprocs it calculates it to be 4 (at least for my large instance). So I think using  automaxprocs would be beneficial here to figure out the default in a container environment.

But GOMAXPROCS has been in use for quite some time in `ko` so I wonder if the prior parallelization code wasn't working as expected?

**Comment by antoineco** [comment]
Oh wow 36 for 8 CPU cores, that's unexpectedly high. Thanks for looking into it!

**Comment by dprotaso** [comment]
@antoineco can you test the above change in our CI?

**Comment by antoineco** [comment]
@dprotaso sure thing.
I [just did](https://app.circleci.com/pipelines/github/triggermesh/triggermesh/1768/workflows/dcf5e55f-6d66-478c-8d21-2463e3917d9d), and it worked like a charm 👍 It seems like `ko` is now building 16 images in parallel on a worker with 8 CPU cores.
Building TriggerMesh's components was super quick (warm build cache) and the resource usage was very reasonable.

Thanks for the patch!
