### ISSUE TITLE
could not parse Go build info: line 4: expected 2 columns for build setting; got 1

### ISSUE THREAD

**Issue by infamousjoeg** [google/ko#651]
I just upgraded my Go version to 1.18 and tried running `ko build` which failed and threw the following error:

```text
❯ KO_DOCKER_REPO=nfmsjoeg ko build .
2022/03/15 23:20:52 Using base gcr.io/distroless/static:nonroot@sha256:80c956fb0836a17a565c43a4026c9c80b2013c83bea09f74fa4da195a59b7a99 for github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app
2022/03/15 23:20:55 Building github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app for linux/amd64
Error: failed to publish images: error building "ko://github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app": could not parse Go build info: line 4: expected 2 columns for build setting; got 1
2022/03/15 23:20:56 error during command execution:failed to publish images: error building "ko://github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app": could not parse Go build info: line 4: expected 2 columns for build setting; got 1
```

I installed `ko` using Homebrew, so I uninstalled it and reinstalled it thinking it was similar to Issue #106, however that did not solve the issue or change the error being thrown.  I have confirmed that `go build .` does successfully build.

**Comment by imjasonh** [comment]
Thanks for reporting this!

This is https://github.com/google/ko/issues/625 -- you should be able to get around this with `go install github.com/google/ko@main` (note: not `@latest`), until we cut a v0.11.0 release, which should be soon.

**Comment by infamousjoeg** [comment]
Thank you @imjasonh, that seems to have gotten me past that error.

It did raise another, however:

```text
Error: failed to publish images: error publishing ko://github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app: PUT https://index.docker.io/v2/nfmsjoeg/k8s-secrets-app-80251e73f499bafd2533f84946cc1c80/manifests/latest: DENIED: unknown manifest class for application/vnd.docker.container.image.v1+json
2022/03/16 08:46:45 error during command execution:failed to publish images: error publishing ko://github.com/infamousjoeg/kubernetes-manifests/apps/k8s-secrets-app: PUT https://index.docker.io/v2/nfmsjoeg/k8s-secrets-app-80251e73f499bafd2533f84946cc1c80/manifests/latest: DENIED: unknown manifest class for application/vnd.docker.container.image.v1+json
```

I'm happy to wait until the next release is cut, if necessary.

**Comment by imjasonh** [comment]
Ah, yeah. That error is coming from some not-yet-released(-because-it's-broken) changes to have `ko` produce OCI images, which Dockerhub (and quay.io, and maybe others) don't like. I'll have to revert that change before releasing v0.11.

**Comment by infamousjoeg** [comment]
`go install github.com/google/ko@main` works! Thank you for this!
