### ISSUE TITLE
Regression in `v0.11.1`: Fails with `could not parse Go build info`

### ISSUE THREAD

**Issue by embano1** [google/ko#666]
I saw couple of issues referencing a similar error, but this should have been resolved in `v0.11.x`. However, we just noticed in our pipelines, that with `v0.11.1` the following error is thrown (again):

```console
error during command execution:error processing import paths in "-": error resolving image references: parsing build info: could not parse Go build info: line 5: expected 3 columns for replacement; got 2
```

Reverting the pipeline back to `v0.11.0` fixes it.

Go version: `v1.17.7`

Example workflow run where this is observed with `v0.11.1`: https://github.com/vmware-tanzu/sources-for-knative/runs/5621359754?check_suite_focus=true

Working run reverting back to `v0.11.0`:
https://github.com/vmware-tanzu/sources-for-knative/runs/5626066023?check_suite_focus=true

**Comment by imjasonh** [comment]
Thanks for reporting this!

It looks like the problematic importpath is `github.com/vmware/govmomi/govc`:

```
$ ./ko version
0.11.1
$ ./ko build github.com/vmware/govmomi/govc --local
...
2022/03/21 10:05:21 error during command execution:failed to publish images: error building "ko://github.com/vmware/govmomi/govc": parsing build info: could not parse Go build info: line 5: expected 3 columns for replacement; got 2
```

(the other image in that YAML builds fine).

Building that binary locally and running `go version -m` (Go 1.17) on it shows there's a replace directive in use:

```
$ go build -o ./ github.com/vmware/govmomi/govc
$ go version -m govc
govc: go1.17.8
	path	github.com/vmware/govmomi/govc
	mod	github.com/vmware/govmomi	v0.24.1-0.20210127152625-854ba4efe87e	
	dep	github.com/google/uuid	v1.3.0	h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
	dep	github.com/kr/pretty	v0.2.1
	=>	github.com/dougm/pretty	v0.0.0-20171025230240-2ee9d7453c02	
	dep	github.com/kr/text	v0.2.0	h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
```

And that's the line causing us trouble -- that's `line 5`, and `expected 3 columns for replacement` comes from [here](https://github.com/google/ko/blob/v0.11.1/internal/sbom/mod.go#L145), parsing a `repLine` (`=>`).

What's even weirder, when I build that package with `go1.18`, it can't be `go version -m`'d with `go1.17`:

```
$ go1.18 build -o ./govc2 github.com/vmware/govmomi/govc
$ go version -m govc2
govc2: go version not found
```

But it can be parsed with `go1.18 version -m`:

```
$ go1.18 version -m govc2
govc2: go1.18
	path	github.com/vmware/govmomi/govc
	mod	github.com/vmware/govmomi	v0.24.1-0.20210127152625-854ba4efe87e	
	dep	github.com/google/uuid	v1.3.0	h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
	dep	github.com/kr/pretty	v0.2.1
	=>	github.com/dougm/pretty	v0.0.0-20171025230240-2ee9d7453c02	
	
	dep	github.com/kr/text	v0.2.0	h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
	build	-compiler=gc
	build	CGO_ENABLED=1
...
```

(note the suspicious newline after the `=>` ... 🤔 )

I wonder if there's some subtle and annoying incompatibility between the output of `go1.17 version -m` and `go1.18 version -m` that we'll need to account for if we want both versions to work.

In the meantime, upgrading to 1.18 or `--sbom=none` should unblock you, though I understand neither may be great answers. I'll dig more and see if I can figure this out.

Thanks again for reporting! 👍

**Comment by embano1** [comment]
Thx for the quick reply! I pinned the `ko` version in my workflow to `v0.11.0` for now.

**Comment by imjasonh** [comment]
In all these cases it would be relevant to say how you installed `ko`, since that determines whether we use the upstream `ParseBuildInfo` that Go provides in 1.18+ or the same code we copied to support pre-1.18.

If you install the prebuilt binary for `0.11.1` (incl using `setup-ko` without `version:tip`) it was built using 1.18, and should use the upstream code. If it was `go install github.com/google/ko@v0.11.1` (or `@latest` or `@main`), the Go version you used to build it matters -- if was Go 1.17, `ko` was installed using our copied fork of the 1.18 code.

**Comment by imjasonh** [comment]
Yeah, if I had to guess, I'd say the newline after each `=>` line is a likely culprit. That doesn't show up if you `go version -m` under Go 1.17.

```
go install golang.org/dl/go1.17@latest
go1.17 download
go install golang.org/dl/go1.18@latest
go1.18 download
diff <(go1.17 version -m $bin) <(go1.18 version -m $bin)
```

I can't imagine that was an intentional choice by the Go team.

**Comment by StevenACoffman** [comment]
Is there also a problem with `ko` if I am using a version of Go (e.g. 1.18) to install ko (`go install github.com/google/ko@latest`) and then change the version of Go back to Go 1.17?

I use ASDF to locally switch different versions of Go since we have some apps using Google AppEngine on its latest Go 1.16 (I know, ugh), and Kubernetes apps on shiny new Go 1.18.

**Comment by StevenACoffman** [comment]
Also, I'm on darwin amd64, but encountered the problem in github actions for Linux.

**Comment by imjasonh** [comment]
> Is there also a problem with `ko` if I am using a version of Go (e.g. 1.18) to install ko (`go install github.com/google/ko@latest`) and then change the version of Go back to Go 1.17?

Maybe? But it sounds like that's not the main issue here.

It sounds like Go-1.18-compatible code might be incapable of parsing Go-1.17-produced output, and maybe vice versa. What a headache.

**Comment by tstromberg** [comment]
@jdolitsky and I took a look at this, and it appears to be an upstream go v1.18 bug with the new `debug.ParseBuildInfo` function and local replace directives. I'm working on a patch for ko & go.
