### ISSUE TITLE
permission denied Runtime.InvalidEntrypoint

### ISSUE THREAD

**Issue by mattn** [google/ko#669]
I pushed images to AWS ECR using ko. But invoking always fail with following errors.

```
START RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Version: $LATEST
IMAGE	Launch error: fork/exec /ko-app/aws-lambda-example: permission denied	Entrypoint: [/ko-app/aws-lambda-example]	Cmd: []	WorkingDir: [/home/nonroot]IMAGE	Launch error: fork/exec /ko-app/aws-lambda-example: permission denied	Entrypoint: [/ko-app/aws-lambda-example]	Cmd: []	WorkingDir: [/home/nonroot]END RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
REPORT RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx	Duration: 19.56 ms	Billed Duration: 20 ms	Memory Size: 128 MB	Max Memory Used: 3 MB	
RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx Error: fork/exec /ko-app/aws-lambda-example: permission denied
Runtime.InvalidEntrypoint
```

**Comment by imjasonh** [comment]
To be able to use `ko`-built images with Lambda, you must use the `aws-lambda-go` framework, as mentioned in the README.

> Or [AWS Lambda](https://aws.amazon.com/lambda/):
> 
> ```aws lambda update-function-code \
>   --function-name=my-function-name \
>   --image-uri=$(ko build ./cmd/app)
> ```
> 
> - Note: The image must be pushed to [ECR](https://aws.amazon.com/ecr/), based on the AWS provided base image, and use the [aws-lambda-go](https://github.com/aws/aws-lambda-go) framework. See [official docs](https://docs.aws.amazon.com/lambda/latest/dg/go-image.html) for more information.

I have an example repo demonstrating this here, if it's helpful: https://github.com/imjasonh/lambda-ko

You may need to change some values in `setup.sh` and `deploy.sh` to match the Lambda function names you want, but as far as I know this should work otherwise.

Let me know (here, or in an issue in that repo) if you have any issues.

**Comment by mattn** [comment]
I tried your `lambda-ko` but same error.

**Comment by imjasonh** [comment]
Are you using the suggested `public.ecr.aws/lambda/provided:al2 ` base image, mentioned in the README, and configured [here](https://github.com/imjasonh/lambda-ko/blob/main/.ko.yaml)?

There may be other supported base images, possibly including `scratch`, but I believe the default distroless image won't work in this case, as you've found.

**Comment by mattn** [comment]
Worked with

```
defaultBaseImage: alpine
```

**Comment by mattn** [comment]
Thanks. BTW, I prefer that ko provide flag to override base image.

**Comment by imjasonh** [comment]
> Thanks. BTW, I prefer that ko provide flag to override base image.

This is possible today with `KO_DEFAULTBASEIMAGE=alpine ko build ...`.

I'm going to close this issue, feel free to keep hacking and let me know if you have any difficulty.
