### ISSUE TITLE
upx with ko?

### ISSUE THREAD

**Issue by xmlking** [google/ko#671]
how to use [upx](https://upx.github.io/) with ko builds?

I currently  use following in Dockerfile
```Dockerfile
RUN go build -a \
    -ldflags="-w -s -linkmode external -extldflags '-static'" \
    -o /app ./$TYPE/$TARGET/main.go

# Compress the binary
RUN upx --best --lzma /app
```

**Comment by imjasonh** [comment]
This is not currently supported, ko builds and packages a standard Go executable, without involving upx.

If we added support, it might make sense as a flag, or as a build config option, but we might need to think about it more.

**Comment by xmlking** [comment]
we might end up needing such `pre/post processors` e.g., **cosign** _images_ and _SBOM_
`config option` might be a better solution for such extensions

**Comment by imjasonh** [comment]
You can already pass the result of ‘ko build` to `cosign sign` (or process the YAML coming out of `ko resolve` to find images to sign).

I'm not sure what you mean by SBOM config options, can you give an example of what you want to accomplish?

**Comment by xmlking** [comment]
I mean, sigh both SBOM(Software Bill of Materials)  artifact and OCI  image produced by **ko**  with **cosign**

**Comment by imjasonh** [comment]
> I mean, sigh both SBOM(Software Bill of Materials) artifact and OCI image produced by **ko** with **cosign**

Sure. Technically it should be possible to write enough glue code to sign SBOMs but I agree it's not clean.

As we start to build cosign functionality into ko itself we'll be able to sign SBOMs too as a first-class feature.

I'm not sure what this has to do with upx though.

**Comment by xmlking** [comment]
agree upx is not related to my comment.  Not sure how much value we gain with `upx`. Anyway it is throwing [Segmentation fault](https://github.com/upx/upx/issues) errors on M1 Macs

was inspired by this blog 
https://programmer.group/using-multistage-and-upx-to-build-smaller-docker-images.html

**Comment by badP0inter** [comment]
Has there been any progress on this?

**Comment by imjasonh** [comment]
> Has there been any progress on this?

Nope.
