### ISSUE TITLE
buildvcs=false must be added to a default build args

### ISSUE THREAD

**Issue by develar** [google/ko#672]
Since Go 1.18 

> The go command now embeds version control information in binaries. It includes the currently checked-out revision, commit time, and a flag indicating whether edited or untracked files are present. Version control information is embedded if the go command is invoked in a directory within a Git, Mercurial, Fossil, or Bazaar repository, and the main package and its containing main module are in the same repository. This information may be omitted using the flag -buildvcs=false.

It means, that go binary maybe changed without actual changes, and also means that building on CI machine is failed (since no Git in path).

Workaround: prepend ko command with `GOFLAGS="-buildvcs=false"`

**Comment by imjasonh** [comment]
It might make sense to add a `-buildvcs` flag to ko, but I think if there's a workaround it might not become a priority. We could document this better though, perhaps in an FAQ section in the readme.

**Comment by blanet** [comment]
Better add `-buildvcs=auto` as a default?

**Comment by imjasonh** [comment]
> Better add something like `-buildvcs=auto` as a default?

I had to look this up myself. It looks like `-buildvcs=auto` is a new option being planned for the next Go 1.18 patch release: see https://github.com/golang/go/issues/51798 and https://github.com/golang/go/issues/51748
