### ISSUE TITLE
The image create time is `49 years ago` when I use KO to build

### ISSUE THREAD

**Issue by zxDiscovery** [google/ko#70]
I follow the step use `ko` build [knative](https://github.com/knative/) images.
Then the images `CREATED` are all `49 years ago`.

```
zxxa/controller-9a0369a1727d6a071312b6fb3887ce48                                                                 latest              34cee1d1afbb        49 years ago        51.1MB
```

**Comment by zxDiscovery** [comment]
cc @mattmoor

**Comment by LinLshare** [comment]
Me too

**Comment by zxDiscovery** [comment]
This issue is solved by https://github.com/google/go-containerregistry/pull/146. So close it.
