### ISSUE TITLE
Use -trimpath for go1.13

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/ko#71]
Currently, the binary built by `go build` includes the file paths for the source files. For most people, GOPATH is in their home directory, so their username is embedded in the resulting binary, which makes reproducible images difficult for us.

In 1.13, we can use `go build -trimpath` to fix this.

See https://github.com/golang/go/commit/74695644e0c38586a85b9b483830c546efbb6642

**Comment by stanleynguyen** [comment]
Hi @jonjohnsonjr Can I take this?

**Comment by jonjohnsonjr** [comment]
Definitely!
