### ISSUE TITLE
ko support podman(cri-o)

### ISSUE THREAD

**Issue by jwcesign** [google/ko#771]
# Environment
k8s with cri-o container engine

# what problem
If with env `KO_DOCKER_REPO=ko.local`, the build img only can be found with docker.
When the pod is launched, there will be a error:`img pull failed`

# what need
ko support podman

**Comment by jwcesign** [comment]
cc @dprotaso @mattmoor

**Comment by imjasonh** [comment]
`ko` uses go-containerregistry's [`pkg/v1/daemon.Write`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/daemon#Write) to load built images into the Docker daemon, which internally uses [`docker/client.Client.ImageLoad`](https://pkg.go.dev/github.com/docker/docker/client#Client.ImageLoad)

Is there an equivalent for Podman? Or is there some way to configure Podman to accept images in the same way as `daemon.Write`?

There was some discussion in go-containerregistry about supporting Podman better, maybe that's a place to start: https://github.com/google/go-containerregistry/issues/998

**Comment by imjasonh** [comment]
Thanks for figuring that out. We should probably document this somewhere more visible... 🤔
