### ISSUE TITLE
How to create OCI image

### ISSUE THREAD

**Issue by sonatard** [google/ko#775]
I used to be able to create an OCI image #623, but it was reverted #653 . Is it possible to create an OCI image now?

**Comment by imjasonh** [comment]
`ko`'s logic is currently to produce an image matching the type of the base image. So if your base image is Docker-typed, `ko` produces a Docker-typed image, etc.

Recently, `ko` changed its default base image to `ghcr.io/distroless/static` (#737), which is equivalent to the previous `gcr.io/distroless/static` in nearly every way, except it's also an OCI-typed image. So with this change, `ko` should start producing OCI-typed images by default.

I'd still like to have a force-OCI (or force-Docker I guess) option, similar to #623, but with better testing and probably a shared implementation in go-containerregistry so other tools can take advantage.

Hope this helps!

**Comment by sonatard** [comment]
Thanks!! I understood. Do you have a next release plan?

**Comment by imjasonh** [comment]
> Thanks!! I understood. Do you have a next release plan?

The [v0.12 milestone](https://github.com/google/ko/milestone/3) is empty, but there are a couple non-technical things I'd like to wait for, so maybe next week. Mainly having more downstream users at head testing stuff out to make sure we're not releasing broken stuff.

For example, #776 was caught by a project that opted in to the new base image already. If they hadn't, we would have released a `ko` that was unable to push to Quay and Gitlab. 🤕 

If you'd like to try out `ko` at head, just `go install github.com/google/ko@main` and let us know if you find anything!
