### ISSUE TITLE
Images are lost when no local docker exists

### ISSUE THREAD

**Issue by mbrancato** [google/ko#799]
I was doing some testing to see if I could use `ko` to build without docker and save the artifact (tar) somehow. I know the documentation says that `ko` "doesn't require docker to be installed", however, in my testing, when using the option `--push=false`, the resulting image is lost. The `go-build` cache remains, but there is no container tar file or other artifact. 

It would be nice for there to be a feature where the tar file could be output as an artifact without being pushed to a registry.

**Comment by imjasonh** [comment]
`--push=false` instructs `ko` not to push the image, so if there's nowhere else the image is written to, it's just gone. This is normally like a dry-run flag in a lot of cases, to prove the build works without any side effect.

If you want to write to a local file, you can use `ko build --tarball out.tar` or `ko build --oci-layout-path=path/to/somewhere` to write the resulting image(s) in an [OCI layout](https://github.com/opencontainers/image-spec/blob/main/image-layout.md) format.

**Comment by mbrancato** [comment]
oh nice, sorry I missed that option in the `--help` output for `ko build`.
