### ISSUE TITLE
Pass environment variable to container

### ISSUE THREAD

**Issue by Yu-Qi** [google/ko#800]
My application layer determine which mode according to environment variable.
Is any way to pass environment variable to container? 
The current workaround is the ldflags, but the changing cost seem high...

**Comment by imjasonh** [comment]
I believe https://github.com/google/ko/pull/632 was an attempt to try to fix this, by letting you configure runtime envs in your `.ko.yaml` file.

I'd still like to do that, but probably not until after we've moved the repo (#791). In the meantime, you have some other options:

1. Pass the env var at runtime:
  - `docker run --env=FOO=bar $image`
  - or for Kubernetes:
  
```
containers:
- image: ko://github.com/org/repo/cmd/app
  env:
  - name: FOO
    value: bar
```

2. After building the image, modify it to set the image's env config, e.g., using [`crane mutate`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_mutate.md):

```
img=$(ko build ./cmd/app)
img=$(crane mutate $img --env FOO=bar)
# deploy $img
```

Neither of these are ideal, but they should work today, until we can get this added to `ko` itself.

**Comment by Yu-Qi** [comment]
Cool. It's a good tutorial!! 
I close it
