### ISSUE TITLE
`ko version` doesn't work with ko installed via `go get`

### ISSUE THREAD

**Issue by adrcunha** [google/ko#85]
According to the README.md, `ko` can be installed/updated using `go get -u github.com/google/ko/cmd/ko`.

However, `ko version` (as impkemented by #81) doesn't work this way:

```
$ go get -u github.com/google/ko/cmd/ko
$ ko version
could not determine build information
```

According to the documentation (https://godoc.org/github.com/golang/go/src/runtime/debug#ReadBuildInfo), the information used to display the version "is available only in binaries built with module support":

https://github.com/google/ko/blob/133ae27c6333361b1bbd7698a7f4867957ecdad4/pkg/commands/version.go#L40

**Comment by ImJasonH** [comment]
I believe the answer to this is going to be to document/require users to install with `GO111MODULE=on go get github.com/google/ko@v0.1.0` or somesuch. This should both make sure it's built with modules support, and explicitly make sure it's a tagged version. If you want to build from HEAD, you can do that too, but your `version` will be `devel` AIUI.

**Comment by adrcunha** [comment]
Looks like the version scheme is good enough for tracking purposes when using `GO111MODULE=on`, as the commit from which it was built is actually tracked:

```
$ GO111MODULE=on go get github.com/google/ko/cmd/ko
go: finding github.com/google/ko/cmd/ko latest
...
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
$ ko version
v0.0.0-20190920163918-f26825fb5ac4
$ git ls-remote https://github.com/google/ko HEAD
f26825fb5ac45444c2b3da8a2a0fc28ca4a6537d	HEAD
```
