### ISSUE TITLE
RFC: Require resolvable import paths to be explicitly marked

### ISSUE THREAD

**Issue by ImJasonH** [google/ko#9]
[The ko model](https://github.com/google/go-containerregistry/blob/5f7b0e4895413d785ff15b84d218d73e8a47866a/cmd/ko/README.md#the-ko-model) as it stands today has led to some user confusion as `ko` has seen wider adoption among new users, as it's become a critical part of development across Knative.

* #34 - simple import paths that aren't based on domain names (e.g., `$GOPATH/src/image/main.go`) can lead to confusing behavior
* #13 - packages that have `func main()` but are not `package main` are not resolved since https://github.com/google/go-containerregistry/pull/229, leading to unresolved github paths in resolved configs
* #10 - typos in package import paths are not caught, and end up in resolved configs
* It's easy to accidentally `kubectl apply -f config/` instead of `ko apply -f config/`, in which case _all_ import paths are passed along unresolved.

The common theme is that while `ko` expects import paths of a certain type, when it erroneously doesn't find a package the user expects it to find, its only recourse is to ignore it and proceed resolving the config. This means that unresolved import paths are passed along, resulting in failed deployments when images inevitably cannot be fetched from, often, github.com.

In [the discussion of #34](https://github.com/google/ko/issues/34#issuecomment-407433496) I proposed a change to the `ko` model to help alleviate this confusion, and I wanted to surface it here for wider discussion.

In short, the proposal is to require config authors to explicitly tag import paths that `ko` should care about with some annotation. Other import path strings (i.e., strings which just happen to also look like import paths) are ignored. If `ko` finds an import path tagged with its annotation which it cannot resolve (because the package is not `package main`, or has a typo, or doesn't exist, etc).

Concretely, I would like to propose that we require users to prepend `ko://` to import paths they expect to be resolved by `ko`. This solves a few problems:

* `ko`'s `IsSupportedReference` becomes `strings.HasPrefix(importpath, "ko://")`
* Import paths that match this but aren't resolvable for any reason result in an error, instead of silently being passed through to the resolved YAML
* Because import paths that don't exist are not passed along, we can avoid a class of failed deployments and erroneous requests to github.com, etc.
* If `ko resolve` on a config finds no import paths it cares about, `ko` should fail, since that might indicate an error (e.g., no import paths were tagged because the tag was misspelled, `ko:/importpath`)

Other options include requiring to-be-resolved import paths with a comment like `image: github.com/foo/bar/cmd/baz # ko`, to a similar effect.

To migrate to this world, we should add an option to relax this requirement, which we can default to true for now, with warnings of increasing urgency until we change the default behavior.

This is a breaking change to the `ko` model, and I think if we decide to make it we should make it soon before the userbase is too large.

@mattmoor @jonjohnsonjr

**Comment by ImJasonH** [comment]
Capturing a conversation I had with @jonjohnsonjr:

How would we detect that a map-type field represents an import path that ko should build and resolve to a digest? Without knowing anything about expected types, ko doesn't know that `image: {...}` is unusual at all. It shouldn't have to know about the expected type, that gets messy fast.

One option is to require a marker key in the map, like so:

```yaml
image:
  ko: yes
  groupId: ...
  artifactId: ...
  version: ...
```

...then it would look for a `ko:yes` then walk back up and resolve based on siblings. That feels gross. 💀 

In any case, we can start with the `ko://` marker first, then expand to support that _and_ map-type markers in the future once we have a better idea what we'd gain from that, and possibly even who else would use it (e.g., Jib).

**Comment by jonjohnsonjr** [comment]
Implemented in https://github.com/google/ko/pull/58
