### ISSUE TITLE
ko is unable to push to a registry with a host and port number

### ISSUE THREAD

**Issue by scothis** [google/ko#93]
When attempting to push images to a registry that uses a hostname and port (like `registry.kube-system.svc.cluster.local:5000`), `ko` fails with the following error:

```
2019/10/01 15:04:17 error creating publisher: failed to parse environment variable KO_DOCKER_REPO="registry.kube-system.svc.cluster.local:5000" as repository: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: registry.kube-system.svc.cluster.local:5000
```

A hostname and port is a valid registry and should be accepted by `ko`

**Comment by scothis** [comment]
The root of the issue is that `ko` treats the value of `KO_DOCKER_REPO` as a valid repository name. It is not a repository, but a base value to derive a repository name. Repositories that specify a host are also expected to include a path to disambiguate from library repositories.

A naive patch would be to append a fake path on the base before validating the repo base, however, this may cause issues with Docker Hub hosted repositories which may only contain a single slash.

**Comment by scothis** [comment]
@jonjohnsonjr thanks for the quick turn around

**Comment by jonjohnsonjr** [comment]
You were the lucky third person to complain about this, so I decided maybe I'm the one that's wrong :P 

cc @ian-mi this should be fixed now

**Comment by jonjohnsonjr** [comment]
The fix for this broke dockerhub defaulting: https://github.com/google/ko/issues/90#issuecomment-566806525

Going to reopen this to track that. I think we can fix this by just re-ordering how we parse things.

**Comment by cezkuj** [comment]
I have got familiar with code looking on the other one. I will create PR for it, if you don't mind. Seems like re-ordering would do the trick, but will double check.
